### ISSUE TITLE
Einheitliches Design für alle Emails, die über BNote versendet werden festlegen

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#103]
Template im BNote-Design erstellen.
Jede Mail sollte Infos zum BNote-System (z.B. URL etc.) enthalten

Das Template könnte in etwa so aussehen:
![email-template vorschlag](https://f.cloud.github.com/assets/2054402/2292522/5889be16-a05a-11e3-9854-d3c27b6c73bd.jpg)

**Comment by mattimaier** [comment]
Now added in Mailing class
