### ISSUE TITLE
german special character displayed wrong

### ISSUE THREAD

**Issue by bernhardkreminski** [mattimaier/bnote#170]
![screen shot 2015-01-16 at 13 30 49](https://cloud.githubusercontent.com/assets/5989776/5776325/03ce79fa-9d86-11e4-8d13-cb96890637c3.png)

found in bnote version for oldschoolbigband/share/music

**Comment by mattimaier** [comment]
Migrationsthema... kann ich nicht allgemeingültig nachstellen.
