### ISSUE TITLE
Hinzufügen von Equipment schlägt fehl

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#177]
![screen shot 2016-06-30 at 11 33 52](https://cloud.githubusercontent.com/assets/2054402/16483876/9cb00152-3eb6-11e6-8453-8f99b4b6d834.png)
![screen shot 2016-06-30 at 11 33 58](https://cloud.githubusercontent.com/assets/2054402/16483877/9cb04680-3eb6-11e6-9339-dcb58d2bd80f.png)

**Comment by mattimaier** [comment]
Problem war in einer regexp.
