### ISSUE TITLE
Buchung lässt sich nur hinzufügen wenn Feld für Steuern gesetzt ist

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#178]
![screen shot 2016-06-30 at 11 35 47](https://cloud.githubusercontent.com/assets/2054402/16483936/ecd263d2-3eb6-11e6-978c-c2dc36b49593.png)
![screen shot 2016-06-30 at 11 35 50](https://cloud.githubusercontent.com/assets/2054402/16483937/ecd2e73a-3eb6-11e6-88e5-ce872f9e805a.png)

**Comment by mattimaier** [comment]
Wird jetzt als default auf 0 gesetzt. Ist besser zu bedienen.
