### ISSUE TITLE
Startseite überarbeiten und übersichtlicher machen

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#199]
Idee: Analog zu #187 die Übersichtlichkeit durch Farben verbessern.
Konzept wird aus der iOS-App übernommen

![screen shot 2016-07-13 at 18 30 18](https://cloud.githubusercontent.com/assets/2054402/16811293/e0d3a98a-4927-11e6-8feb-94fad96ae018.png)

**Comment by sotpt** [comment]
Aktueller Entwicklungsstand:
![screen shot 2016-07-13 at 19 22 49](https://cloud.githubusercontent.com/assets/2054402/16812859/4c454460-492f-11e6-9107-76d0917d6ef5.png)

@mattimaier: Die Idee ist, alle Events, bei denen der User noch zusagen muss hervorzuheben. Hast du eine bessere Idee als den roten Rahmen?

**Comment by mattimaier** [comment]
Sieht gut aus für Proben:
![bnote___start](https://cloud.githubusercontent.com/assets/1818429/17356784/a3208c38-5959-11e6-9c1b-55455cac50b1.png)

Sieht gut aus für Konzerte:
![bnote___start](https://cloud.githubusercontent.com/assets/1818429/17356808/c0630802-5959-11e6-8000-84de26a327a5.png)

Analog ist beim Konzert die Teilnahme einfach noch ein Link
