### ISSUE TITLE
Startseite: Ausgrauen von Events an denen der User nicht Teilnimmt

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#200]
![screen shot 2016-07-13 at 19 27 03](https://cloud.githubusercontent.com/assets/2054402/16812987/e1be16e8-492f-11e6-99dc-c6e0ab08792d.png)

Ein User, der eine Probe oder ein Konzert abgesagt hat interessiert sich meistens nicht mehr für das Event, daher könnte das Ausgrauen von abgesagten Events die Übersichtlichkeit erhöhen.

@mattimaier: Was hältst du von dieser Idee?

**Comment by mattimaier** [comment]
siehe #199
