### ISSUE TITLE
Nachricht speichern erzeugt Fehler

### ISSUE THREAD

**Issue by FORMEL** [mattimaier/bnote#225]
**Nachricht speichern**
> Warning: file_put_contents(data/nachrichten.html): failed to open stream: Keine Berechtigung in /www/htdocs/w010609e/bandorga/BNote/src/data/modules/nachrichtendata.php on line 49

**Comment by mattimaier** [comment]
Das ist vermutlich, weil die Berechtigungen in `BNote/data/nachrichten.html` nicht stimmen. Kannst du das bitte prüfen? Schau, dass sie auf -rw-rw-r-- (664) stehen und die Gruppe zu deinem Apache-User passt.

**Comment by FORMEL** [comment]
Leider nein. Ich habe sowohl den User als auch die Rechte überprüft (und diese sowohl in src/data/modules als auch im normalen Data-Ordner (nachrichten.html) einmal testweise auf 775 gesetzt). Die Fehlermeldung bleibt.

Soll ich Dir einmal einen FTP-User einrichten?

**Comment by mattimaier** [comment]
Ich bitte um eine Nachricht an mail@bnote.info.
Ich glaube nicht, dass es sich um einen Implementierungsfehler handelt.
Was du als letztes versuchen kannst ist 666 -> vielleicht ist ja einfach nur der Nutzer und die Gruppe falsch?

**Comment by FORMEL** [comment]
Das Umstellen der folgenden Dateien auf 666 hat das Problem beseitigt.
Es wäre jedoch seltsam, wenn das Problem mit den Standardrechten nur bei mir auftauchen würde, oder?

> /BNote/data/nachrichten.html
> /BNote/src/data/modules/nachrichtendata.php
