### ISSUE TITLE
Übersicht Proben/Konzerte nach Stimmen

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#228]
**User Request**
_Erstens eine bessere Admin-Übersicht über die Teilnehmer an Konzerten/Proben. Hier hat der singste-Kollege eine sehr schöne Ansicht geschaffen – siehe Screenshot. Hier kann ich sofort und nach Stimmen (Instrumenten) geordnet und sehr übersichtlich sehen, wer welchen Status hat: Ja/Nein/vielleicht/nicht nicht gemeldet. Das ist dann ja nur eine Sache der Seitengestaltung. Sowas wünsche ich mir jedenfalls auch..._

![bildschirmfoto 2016-09-18 um 17 07 55](https://cloud.githubusercontent.com/assets/1818429/18640297/c29df420-7e97-11e6-84d2-c5195f1645e0.jpg)

**Comment by FORMEL** [comment]
Toll fände ich auch eine Teilnehmerübersicht auf Seiten der Musiker.
Zumindest könnte man diese in Zahlen schon auf der Starseite ausgeben.

Beispiel:
-------------------------------------------
Dienstag, 04.10.2016 19:30 
**Du nimmst an der Probe teil.** 
_Eingeladen: 5 / Bestätigt: 4 / Vielleicht: 1_
Neuer Kommentar

-------------------------------------------
Der Punkt "Du nimmst an der Probe teil" ist ja rein faktisch eigentlich die am wenigsten interessante Info (das sollte man auch so wissen). Vielmehr interessiert es ja, ob eine spielfähige Gruppe zusammen kommen kann. Eine gute Blaupause für die Organisation von Proben/Terminen ist sicher www.unserteam.de

Grüße Sascha

**Comment by mattimaier** [comment]
Für Chöre und andere Ensembles (z.B. Tanzgruppen) wäre es hier gut, wenn es nicht "Instrumente" oder "Stimmen" heißt, sondern "Rollen"
