### ISSUE TITLE
Anzeige von Pflicht-/Optionalfeldern

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#233]
**User Request**
_Als "Fehler" ist mir noch aufgefallen, dass es bei einigen Dialogboxen (Song hinzufügen beispielsweise) zu Fehlermeldungen kommt, wenn nicht alles eingetragen wird. Hier wäre es hilfreich zu sehen, welche Felder verbindlich sind (nicht immer weiß ich z.B. während des Eintragens die Tonart oder die Dauer) und welche nicht._

Es gibt ja jetzt das Feature im Feld-Array wo man das nur einstellen muss...

**Comment by mattimaier** [comment]
Felder für Song gekennzeichnet

**Comment by pandeira** [comment]
required field "Komponist / Arrangeur" not marked (tested with version 3.3.2 and 3.4.0)
