### ISSUE TITLE
Anlegen einer Probe erzeugt Duplicate entry '6-2' for key 'PRIMARY'.

### ISSUE THREAD

**Issue by FORMEL** [mattimaier/bnote#234]
> Fehler
> The database query has failed:
> Duplicate entry '6-2' for key 'PRIMARY'.
> Debug:INSERT INTO rehearsal_contact VALUES (6, 7), (6, 4), (6, 2), (6, 5)

User hat alle Rechte

**Comment by mattimaier** [comment]
Danke fürs melden. Wird eingeplant zu ändern.

**Comment by mattimaier** [comment]
Cannot reproduce
