### ISSUE TITLE
Button-Farben der Navigationsleiste ändern

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#235]
**User Request**
Darüber hinaus würde ich empfehlen, alle Buttons im Kopfbereich der Module (bis auf den "zurück"-Button) mit einer abweichenden Farbe zu versehen.
Dies würde die GUI deutlich übersichtlicher machen.
Siehe z.B. Probe-Modul > ausgewählte Probe, bei dem es zwei Menü-Strukturen gibt (Kopfbereich / Inhaltsbereich (Details, Einladungen, Teilnehmer, Stücke)).

**Comment by sotpt** [comment]
Alternatives Design:
https://github.com/mattimaier/bnote/pull/257

<img width="1579" alt="screen shot 2017-03-23 at 20 07 05" src="https://cloud.githubusercontent.com/assets/2054402/24265643/82c8c466-1004-11e7-849b-d40542e3984b.png">

@mattimaier Die dunkelblaue Leiste fügt sich etwas besser in das Gesamt-UI ein

**Comment by mattimaier** [comment]
Sieht echt gut aus :-)
