### ISSUE TITLE
Viele Fehlermeldungen - Rechte von Dateien und Ordnern

### ISSUE THREAD

**Issue by FORMEL** [mattimaier/bnote#237]
Hallo. Ich bekomme an allen Ecken und Enden Fehlermeldungen.
Ich vermute, dass es an fehlerhaft gesetzten Datei- und Ordnerrechten liegt, habe aber keine Ahnung, wo ich eine Gesamtübersicht über die benötigten Rechte finden kann.
## Hier ein paar Beispiele von Fehlermeldungen:

**Share > Ordner erzeugen >**
`** Warning: mkdir(): Keine Berechtigung in /www/htdocs/w010609e/bandorga/BNote/src/presentation/widgets/filebrowser.php on line 372`

**Konzert hinzufügen**
`Fehler
The database query has failed:
Unknown column 'title' in 'field list'.
Debug:INSERT INTO concert (program, contact, location, title, begin, end, approve_until, notes) VALUES (1, 9, 4, "Testgig 1", "2016-09-29 18:00:00", "2016-09-29 18:00:00", "2016-09-29 18:00:00", "Testgig 1")`

**Website Inhalte > Band bearbeiten**
`Warning: file_get_contents(data/webpages/band.html): failed to open stream: Datei oder Verzeichnis nicht gefunden in /www/htdocs/w010609e/bandorga/BNote/src/presentation/modules/websiteview.php on line 82
`

**Comment by mattimaier** [comment]
Hallo @FORMEL,
Danke für die Messages. Eine Übersicht der Berechtigungen findest du in der readme.txt im Ordner BNote. Aber hier konkretere Hilfen zu deinen Problemen:
* **Share > Ordner erzeugen**: Der Benutzer deines Hostings passt nicht mit BNote zusammen. Du hast irgendwo falsche Berechtigungen eingestellt (ggf. ist das auch eine Konfiguration deines Hosters).
* **Konzert hinzufügen**: Bitte stelle sicher, dass du die neueste BNote Version hast. Welches Datenbanksystem hast du genau? Ich habe es nur mit MySQL getestet - ich könnte mir vorstellen, dass `title` in anderen (oder ggf. neueren) Systemen zu Problemen führt. Dann übrigens an vielen Stellen.
* **Website Inhalte > Band bearbeiten**: Das ist vermutlich das gleiche Problem wie Ersteres. Bitte Berechtigungen prüfen.

Leider weiß ich nicht wie ich dir hier besonders - programmatisch - weiterhelfen kann. Sonst würde ich das gerne tun. Du kannst mir aber einfach mal eine Mail auf support@bnote.info schreiben. Dann können wir ggf. einen Skype Call machen.
