### ISSUE TITLE
Link bei Kalender Abonnement mit Version 3.x fehlerhaft

### ISSUE THREAD

**Issue by bernhardkreminski** [mattimaier/bnote#238]
Kalender abonnieren liefert link:

webcal://www.HOST.de/bnote/src/export/calendar.ics?user=USER

korrekter link wäre:

webcal://www.HOST.de/bnote/BNote/src/export/calendar.ics?user=USER

mit Old School Big Band Instanz getestet

**Comment by mattimaier** [comment]
@bernhardkreminski Bitte gib @sotpt Bescheid, dass er die config/config.xml Datei überprüft. Vielleicht wurde nicht richtig upgegraded. Aber ich überprüfe ob es hier ein Problem gibt. In meinen Instanzen war alles ok.

**Comment by mattimaier** [comment]
vermutlich gleiches problem wie #241
