### ISSUE TITLE
Share: Sonderzeichen in Dateien downloaden und zippen

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#239]
**User Request**
ich habe unter Share einen Ordner angelegt und MP3-Dateien hochgeladen; leider diverse mit dem "&" im Dateinnamen, z.B. KC & the Sunshine... Earth, Wind & Fire usw. Problem ist jetzt das der Download dieser Dateien nicht läuft, damit auch das ZIP-Archiv des Ordners nicht und löschen kann man die Dateien auch nicht - beim Anklicken des Lösch-Buttons kommt folgende Meldung:
Fehler

Es wurde ein vermeintlicher Angriff festgestellt.
Sollte diese Meldung weiterhin auftreten, wenden Sie sich bitten an Ihren Systemadministrator

und BNote stürzt dann ab.

**Comment by mattimaier** [comment]
Das Problem ist ein Fehler im URL-Encoding in PHP. Die Dateien müssten erneut hochgeladen werden (keine Lösung für Altdateien), aber für neue Dateien sollte es ab v3.2.0 funktioneren.

**Comment by sotpt** [comment]
@mattimaier Die Textdatei Test&@#.txt lässt sich hochladen, wird aber als Test@#.txt ohne das & angezeigt
Der Download-Link http://test.bnote.info/BNote/src/data/filehandler.php?file=//Musik/Test@#.txt
zeigt damit ins Leere

**Comment by mattimaier** [comment]
Das Problem ist der "#" und der "&" Character der in PHP nicht richtig escaped wird wohl. Keine Ahnung warum. Hab jetzt 2 Fixes eingebaut. Wird schon passen ;-)
