### ISSUE TITLE
Mobile Login on Android never succeeds

### ISSUE THREAD

**Issue by bernhardkreminski** [mattimaier/bnote#256]
Using the mobile version of Bnote on Android, the login does not work - an error message is shown.
By switching to the desktop version the login succeeds.

Occured on Bnote instance of the Old School Big Band

**Comment by mattimaier** [comment]
Die Android App wird seit Version 3 nicht mehr unterstützt. Ihr habt bei der OSBB Version 3.1.0 - die müsste @sotpt eh mal updaten.
