### ISSUE TITLE
Zeitzonen im Kalender sind falsch

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#259]
Beispiel:
Probe um 19:30 (Zeitzone Berlin)
Anzeige im Kalender: 21:30 (Calendar macOS)

<img width="291" alt="screen shot 2017-03-24 at 00 05 06" src="https://cloud.githubusercontent.com/assets/2054402/24273952/a84c775c-1025-11e7-924e-94b315294b56.png">

**Comment by mattimaier** [comment]
Kannst du bitte das Test-System in deinen Mac-Kalender importieren und schauen ob es jetzt geht. Ich befürchte, dass für alle anderen jetzt die Zeitzone falsch ist...

**Comment by sotpt** [comment]
Die Events werden immer noch 2 Stunden zu spät angezeigt

**Comment by mattimaier** [comment]
Dann lass ich die Implementierung wie sie ursprünglich war. Auf meinem iPhone funktionierts und in den Google Kalendern auch. Warum ausgerechnet der Mac-Kalender hier Probleme macht, weiß keiner. Auch nicht in diversen Online-Foren.

**Comment by HenningKuehl** [comment]
Gibt es dazu mittlerweile eine Lösung?
In Outlook werden die Zeit nämlich auch Falsch angezeigt. Genau zwei Stunden nach hinten versetzt.
