### ISSUE TITLE
Einphasung: Kontakte nach Gruppen aufteilen

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#268]
Bei der Einphasung wäre eine Filterung nach Gruppen sinnvoll, damit nicht immer alle 170 Kontakte auftauchen. Das wäre eine Wunscherweiterung für die Zukunft.

**Comment by mattimaier** [comment]
Impliziete Funktion mit Beschreibung hinzugefügt.

**Comment by mattimaier** [comment]
Funktioniert nicht, da die Verarbeitungslogik noch nicht mit Gruppen umgehen kann!

**Comment by maiermarina** [comment]
funktioniert:
![bildschirmfoto 2017-04-23 um 13 54 12](https://cloud.githubusercontent.com/assets/27913238/25313342/d198db0e-282c-11e7-936a-1bea2ad001f0.png)
![bildschirmfoto 2017-04-23 um 13 57 22](https://cloud.githubusercontent.com/assets/27913238/25313343/d3759fca-282c-11e7-8f19-99f8e8f884c8.png)
