### ISSUE TITLE
Probenübersicht Duplicates

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#270]
**User Comment**
In der neuen und übrigens sehr praktischen Probenübersicht werden die Instrument-Komponenten jeweils so oft angezeigt, wie es Personen zu dem jeweiligen Instrument gibt. Wenn es z.B. 4 Trompeten gibt, wird der Trompetenblock auch vier Mal angezeigt. Das Problem habe ich mit einem DISTINCT in der Datenbankabfrage in der Funktion getUsedInstrument in probendata gelöst.

**Comment by maiermarina** [comment]
Instrumenten-Komponenten werden nicht mehr dupliziert:
![bildschirmfoto 2017-04-23 um 13 40 14](https://cloud.githubusercontent.com/assets/27913238/25313199/7d2af7ca-282a-11e7-890f-9f37483e195b.png)

evtl. Ausrichtung in der Zelle/Block noch anpassen, z.B. mittig, siehe Ausrichtung Akkordeon

**Comment by maiermarina** [comment]
passt
