### ISSUE TITLE
Vergangene Proben zeigt auch künftige Proben

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#271]
Wenn man auf Vergangene Proben drückt (bei "vergangene" hat sich übrigens ein Rechtschreibfehler eingeschlichen), erhält man auch die zukünftigen Proben. Dies habe ich mit einer zusätzlichen Bedingung end < now() in getPastRehearsals in probendata gelöst.

**Comment by maiermarina** [comment]
in vergangene Proben werden keine zukünftigen Proben angezeigt:
![bildschirmfoto 2017-04-23 um 13 31 29](https://cloud.githubusercontent.com/assets/27913238/25313146/3d1ce112-2829-11e7-8050-6906c4aef7bd.png)

allerdings funktioniert der Filter nicht. es werden trotzdem alle vergangene Proben angezeigt.

**Comment by maiermarina** [comment]
funktioniert
