### ISSUE TITLE
Rechtschreibfehler in UserView

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#272]
In userview: Rechtschreibfehler Button "Akiver Benutzer" -> Ak**t**iver Benutzer

**Comment by maiermarina** [comment]
done:
![bildschirmfoto 2017-04-23 um 13 24 51](https://cloud.githubusercontent.com/assets/27913238/25313113/4ebad10a-2828-11e7-88bb-cfc9f85b385f.png)
