### ISSUE TITLE
Kalenderview mit Startseite-Popup

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#273]
**User Comment**
Wenn man im Kalender auf einen Eintrag drückt, aber z.B. kein Recht für das Probenmodul hat, wird eine Fehlermeldung angezeigt. Könnte man dort vielleicht ein ähnliches Popup anzeigen wie auf der Startseite?

**Comment by maiermarina** [comment]
kein Pop-up, aber es werden unter dem Kalender Details zum Eintrag angezeigt wenn man diesen anklickt:
![bildschirmfoto 2017-04-23 um 13 17 32](https://cloud.githubusercontent.com/assets/27913238/25313060/4a3313fa-2827-11e7-90cd-3e1f8d3c3184.png)

bitte bei Kalendereintrag die Uhrzeit im Format 19:00 anzeigen.

**Comment by maiermarina** [comment]
funktioniert
