### ISSUE TITLE
Startseite: Konzertdetails verbessern

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#275]
* Auf der Startseite kann man sich zwar die Teilnehmer einer Probe anzeigen lassen, aber nicht die Teilnehmer eines Konzertes.
* Es wäre gut, wenn "Antwort bis" angezeigt wird.
* Außerdem werden die Anmerkungen bei einem Konzert nicht angezeigt.

**Comment by maiermarina** [comment]
Teilnehmer eines Konzerts können nun angezeigt werden, "Notizen" und "Teilnahme angeben bis" sind enthalten:
![bildschirmfoto 2017-04-23 um 11 33 55](https://cloud.githubusercontent.com/assets/27913238/25312785/c20ee2c4-2821-11e7-915f-d22ab8898d8a.png)

wenn man sich die Teilnehmer anzeigen lässt, werden diese aufgelistet:
![bildschirmfoto 2017-04-23 um 12 27 48](https://cloud.githubusercontent.com/assets/27913238/25312791/e2b95a4a-2821-11e7-825e-ae0ff6bba3ba.png)

allerdings wir kein Datum und keine Uhrzeit des Konzerts und auch nicht der Titel des Konzerts angezeigt.

**Comment by maiermarina** [comment]
funktioniert
