### ISSUE TITLE
Startseite: Stücke zum Üben hat tech. Label

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#276]
![2017-04-17_18h25_00](https://cloud.githubusercontent.com/assets/1818429/25095250/2e8b517a-239b-11e7-90cf-3371d3f042d7.png)

**Comment by maiermarina** [comment]
Techn. Label nicht mehr vorhanden, wird nun richtig angezeigt, getestet für Probe 04.05.2017:
![275](https://cloud.githubusercontent.com/assets/27913238/25312374/b1691502-2817-11e7-8c2b-51c972d0b141.png)
Allerdings werden nicht für alle Proben Stücke zum Üben angezeigt, obwohl dies unter "Proben" hinterlegt wurde, z.B. für den 11.05., 20.07, 27.07. :
Screenshot aus Reiter Probe:
![zu 275 klappt nciht bei allen proben_2](https://cloud.githubusercontent.com/assets/27913238/25312376/ce17952a-2817-11e7-9eba-fb075df8cfaa.png)
Screenshot von Startseite:
![zu 275 klappt nicht fur alle proben](https://cloud.githubusercontent.com/assets/27913238/25312378/d13a6066-2817-11e7-9852-a5672a0ffc5a.png)

**Comment by maiermarina** [comment]
funktioniert jetzt
