### ISSUE TITLE
Repertoire-Aufruf gibt Fehlermeldung

### ISSUE THREAD

**Issue by rbrunni** [mattimaier/bnote#277]
Hello, 
after I upgraded to Ver. 3.20 I can not access the Repertoire section any more.
It pretty much worked with the old version 3.15.
When accessing the Repertoire field, I get the following error message:

Fehler
The database query has failed:
Unknown column 'song.setting' in 'field list'.
Debug:SELECT song.id, song.title, song.length, song.bpm, song.music_key, song.setting, song.notes, genre.name as genrename, composer.name as composername, status.name as statusname FROM song, genre, composer, status WHERE song.genre = genre.id AND song.composer = composer.id AND song.status = status.id AND length >= 0 ORDER BY title

Also upgrade to 3.21 did not solve the issue.
Thanks for your help
rbrunni

**Comment by mattimaier** [comment]
Problem is a missing column in the installer script around these lines:
https://github.com/mattimaier/bnote/blob/master/BNote/install.php#L454

**Workaround**
Just use the update_db.php script and execute it once. This adds the column.
