### ISSUE TITLE
Diverses

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#291]
## Bugs
- die Pfeile nach links und rechts im DatePicker für eine Auftritt funktionieren nicht
- bei Android wird durch den Zurück Button die Web-App sofort geschlossen und nicht auf die letzte Seite gesprungen, sehr nervig zur Bedienung

## Features
- Möglichkeit zur Teilnahme an Auftritten und Proben deaktivieren, nutzen es im Musikverein als reine Informationsquelle
- Teilnahme an Probe standardmäßig auf "Zusagen" stellen, sodass man aktiv "Absagen" muss

**Comment by mattimaier** [comment]
@HenningKuehl 
* Wo funktionieren die DatePicker nicht? Hast du ein Beispiel?
* Die UI5 Version in 3.3.0 hat noch ein paar Fehler, das sollte demnächst behoben sein
* Teilnahmemöglichkeiten abschalten ist viel Aufwand und ich sehe den Nutzen nicht. Wenn man BNote nur als Info-Tool verwendet, dann ist es doch egal ob das angezeigt wird doch nicht... Wo ist hier das konkrete Problem?
* Aus Erfahrung mit vielen anderen Ensembles ist die aktive Zu-/Absage besser. Sonst wird's für manche zur Gewohnheit zu kommen/nicht zu kommen.

**Comment by HenningKuehl** [comment]
- Beim Hinzufügen eines Auftritts funktionieren die Pfeile im DatePicker nach links und rechts um den Monat zu wechseln nicht.
- Das Abschalten der Teilnahmemöglichkeit war nur so eine Idee. Da wir die Funktion nicht nutzen, wäre es vielleicht auch schön, wenn sie gar nicht erst angezeigt wird. Mega cool wäre natürlich, wenn man das pro Probe einstellen könnte. Aber wenn das zu viel Aufwand ist, ist das natürlich nicht sonderlich schlimm.
- Bei uns heißt es, wenn man sich nicht abmeldet, dann kommt man. Dann brauch man sich nicht aktiv für jede Probe anmelden.

- Ein weiteres Feature wäre, wenn man für einen Auftritt noch eine "Treffzeit" angeben könnte. Sodass man zwischen Auftrittsbeginn und Treffzeitpunkt unterscheiden kann.

**Comment by mattimaier** [comment]
Danke für die Kommentare. Punkte 1 und 4 versuche ich zu lösen.
Punkt 2 merke ich mir und wenn nochmals jemand danach fragt, dann würde ich das Feature umsetzen.
Punkte 3 macht Sinn, aber dafür wüsste ich nicht was man bauen sollte...

**Comment by mattimaier** [comment]
*Test*
* Datepicker-Pfeife funktionieren wieder
* Meeting time muss auf Start angezeigt werden
