### ISSUE TITLE
Fehlende Informationen: Auftritt

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#295]
## Outfit
Die Informationen, welches Outifit getragen werden soll, fehlt im Start Modul und im Kalender. Leider nur in der Detail Ansicht sichtbar.

## Treffpunkt (Zeit)
Fehlt im Kalender und in der mobilen Ansicht.

**Comment by mattimaier** [comment]
In mobiler Ansicht ist in den Auftrittsdetails das Outfit bereits vorhanden.
