### ISSUE TITLE
Share Modul

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#308]
Aktuell hat das Share Modul noch einige kleinere Fehler, die aber so viel Auswirkung haben, dass es sehr unangenehm ist damit zu arbeiten.
_Im Issue #301 hatte ich auch schon mal kurz was dazu geschrieben._

# Bugs
## Fehlermeldung
Es gibt eine Fehlermeldung, die bei verschiedenen Aktionen auftritt.
> ### Fehler
> Es wurde ein vermeintlicher Angriff festgestellt.
> Sollte diese Meldung weiterhin auftreten, wenden Sie sich bitten an Ihren Systemadministrator.
Das Löschen einiger Dateien funktioniert nicht und das öffnen einiger Ordner funktioniert nicht.

## Löschen Symbol
Das Löschen-Symbol wird auch beim Pfeil um zurück in den übergeordneten Ordner zu gelangen angezeigt.

## Aufhängen beim zurück gehen
Die Website hängt sich beim zurück gehen in einen übergeordneten Ordner oft auf und brauch ein gewisse Zeit um wieder bedienbar zu sein. Das macht das bedienen des Share-Moduls sehr schwerfällig.

## IOS Berechtigung
Unter dem mobilen IOS Browser ist es nicht möglich das Share-Modul zu benutzen, da immer eine Fehlermeldung kommt, dass der jeweilige Nutzer keine Berechtigung für das Modul hat.

# Features
## Standardgruppe
Schön wäre es, wenn im Share-Modul zu Beginn der Ordner der Standardgruppe aus der Konfiguration ausgewählt wäre. Zusätzlich wäre eine Markierung der ausgewählten Gruppe hilfreich.

**Comment by mattimaier** [comment]
Für die Bugs bitte neue einzelne Tickets erstellen.
Das Feature habe ich als separates Ticket aufgenommen: #313
