### ISSUE TITLE
Individuelle Kontaktfelder

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#316]
Eigens angelegte Kontaktfelder können nicht im Modul "Kontaktdaten" vom User selber bearbeitet werden, sondern nur im Modul "Kontakte".

**Comment by HenningKuehl** [comment]
Achso. Finde ich eine gute Idee.

**Zusätzlicher Vorschlag**
Eine "readonly" Funktion. Es kann quasi nur der Admin das Feld bearbeiten, es können aber trotzdem alle die Information sehen.

**Comment by mattimaier** [comment]
*Specs*
* 2 neue Felder für benutzerdefinierte Felder:
  * "Freigegeben": Zeigt ob andere dieses Feld sehen können
  * "Admin-Bearbeitung": Gibt an, ob nur ein Administrator dieses Feld bearbeiten kann
* Module: Kontakte, Mitspieler, Kontaktdaten
* _Fälle_
  * Freigegeben = 1, Admin = 1: alle Module zeigen dieses Feld, nur Admin kann Feld bearbeiten in Kontakte
  * Freigegeben = 1, Admin = 0: alle Module zeigen dieses Feld, jeder (inkl. eigenem User in Kontaktdaten) kann das Feld bearbeiten
  * Freigegeben = 0, Admin = 1: Feld nur in Kontakte sichtbar, nur Admin kann Feld bearbeiten
  * Freigegeben = 0, Admin = 0: Feld nur in Kontakte sichtbar, jeder (inkl. eigenem User in Kontaktdaten) kann das Feld bearbeiten

**Comment by mattimaier** [comment]
Admin-Funktionalität ist sehr speziell. Nur wenn noch mehr für dieses Feature stimmen, wird es ggf. umgesetzt.
