### ISSUE TITLE
DSGVO: E-Mail Link mit Einverständniserklärung

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#317]
*Features*
* Kontaktgruppen auswählen -> automatisch E-Mail mit Link wird versandt auf Seite wo der Kontakt draufklicken kann, seine Daten aktualisieren und einsehen und bestätigen, dass es für ihn OK ist diese zu verarbeiten
* Einverständnisseite auch als "Stand-Alone" für jegliche Kontakte, die dann mittels E-Mail-Adresse zugeordnet oder direkt angelegt werden
* Auf Website damit werben

**Comment by bwl21** [comment]
Meines Erachtens braucht man da eine Zustimmungsmatrix, es sei denn man fährt ein alles oder nichts - Ansatz. Die Zustimmungsmatrix umfasst die Einzelzustimmungsart für den Prozess und die Dokumentation der Einverständnis.

z.B.

Email - Kommunikation: Vertrag | online | email | nicht
Tel-Kommunikation: Vertrag | online | email | nicht
post-Kommunikation: trag | online | email | nicht
bildveröffentlichung | Vertrag | online | email | nicht
Datenspeicherung | Vertrag | online | email | nicht
usw.

Das heisst die Art der Verarbeitung sollte nicht hart verdrahtet sein, sondern, auch irgendwie konfigurierbar. Andererseits kann man ohne Hartverdrahtung kaum irgendwelche filter dran hängen.

Die Dokumentation der Zustimmung könnte man zur Not fest verdrahten:

Vertrag heisst, dass mit den Ensemblemitgliedern ein Vertrag geschlossen wurde in dessen Rahmen die Zustimmung erfolgt.

Online heisst, dass das Mitglied die Zustimmung in einer online-Maske gegeben hat

email heisst, dass das Mitglied die Zustimmung über eine Email gegeben hat.

nicht heisst, dass der Verarbeitung widersprochen wurde

offen heisst, dass noch keine Entscheidung vorliegt
