### ISSUE TITLE
Berechtigungen Share Modul

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#322]
Wir benutzen den Share Bereich mit knapp 80 Musikern in unserem Orchester und deswegen wäre es schön, wenn es eine Möglichkeit gibt, dass nicht jeder einfach andere Dateien löschen kann. 

Entweder man müsste Berechtigungen vergeben können oder es kann nur derjenige die Datei löschen der sie auch hochgeladen hat bzw. ein Admin.

**Comment by mattimaier** [comment]
Die Möglichkeit gibt es schon:
![2018-09-02_17h11_33](https://user-images.githubusercontent.com/1818429/44957481-58720500-aed3-11e8-8e28-e66d4cbb528d.png)
