### ISSUE TITLE
Regelmäßige Auftritte

### ISSUE THREAD

**Issue by xalbrec** [mattimaier/bnote#324]
Ich benötige eine Funktion, mit der ich regelmäßige (wöchentliche) Auftritte/Gottesdienste mit meinem Chor planen kann. Zu einem Auftritt gehören SängerInnen, 1 Dirigent und ein Orgelspieler
Folgende Daten müsste ich also erfassen können:

- Dirigent/Leiter während des Auftritts (für den Chor gibt es 1 Hauptdirigenten und aus der Gruppe der Mitglieder mehrere stellvertretende Dirigenten)
 — Möglichkeit die Funktion des Dirigenten mit einem Kontakt verknüpfen zu können (evtl. als benutzerdefinierten Feld, hier fehlt mir aber die Möglichkeit eine „Nachschlageliste“ zu hinterlegen)
 — Einladung an Personen mit dieser Funktion (die Zusammenfassung als Gruppe würde funktionieren)
— die Kontakte, die ich als Dirigent einlade werden aber auch gleichzeitig als Sänger/In eingeladen
— Orgelspieler für den Auftritt, Person ist wieder Mitglied im CHor in übernimmt ggf. Nur diese zusätzliche Aufgabe 

Habe versucht das über Probenstrecken zu machen, funktioniert aber nicht richtig.

**Comment by mattimaier** [comment]
Vorschlag:
* Proben erhalten ein neues Feld "Dirigent"
* Kontakte erhalten ein neues Feld "kannDirigent"
* Die Konfiguration erhält ein Feld für den "Standarddirigenten"
* Bei der Erstellung einer Probe (oder Probenstrecke) gibt es ein Auswahlfeld für den Dirigenten
* In der Probenübersicht wird der Dirigent mit angezeigt
* In den Details auf der Startseite wird der Dirigent angezeigt
* Im Kalenderexport wird der Dirigent in den Notizen vermerkt

**Comment by xalbrecht** [comment]
Das wäre für die Probenplanung eine gute Lösung. Vielen Dank.

**Comment by bwl21** [comment]
> * Kontakte erhalten ein neues Feld "kannDirigent"

M.e. könnte (sollte) man das generalisieren. Ein Kontakt kann ja verschiedene Fähigkeiten haben. Er kann sogar verschiedene Instrumente spielen. Vielleicht kann man diese Fähigkeit und auch das Instrument ähnlich wie die Gruppen abbilden.

**Comment by mattimaier** [comment]
Dies ist nun für Proben umgesetzt. Für Auftritte schlage ich vor, dass man ein benutzerdefiniertes öffentliches Feld macht (siehe #325 ) um diese Anforderung umzusetzen.
