### ISSUE TITLE
Freikonfigurierbare Felder für Konzerte, Reservierungen und Proben

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#325]
So wie für Kontakt benutzerdefinierte Felder existieren, sollten diese auch für diese Objekte freigeschaltet werden:
* Konzerte
* Reservierungen
* Proben 
Die Konfiguration kann bleiben wo und wie sie ist. Erweiterungen sind jedoch auf vielen Screens notwendig.

**Comment by xalbrecht** [comment]
bitte auch für das Repertoire erweitern:

- da mein Repertoire aus einer Sammlung / einem Buch kommt, besitzen die Titel "Nummern", die ich gerne mit pflegen würde.

**Comment by bwl21** [comment]
Ich unterstütze ausdrücklich die Anforderung von xalbrecht

Hintergrund: Wen man in einem Ensemble nicht nur eigene Stücke spielt, hat man sofort das Problem legal mit den Noten umzugehen, d. h. anzugeben, aus welchem Notenbuch (Quelle) man das Stück entnimmt. Daher ist es erforderlich, für jedes Stück im Repertoire zu erfassen aus welcher Quelle man spielt. Die Teilnehmer müssen sich dann die Noten aus exakt dieser Quelle beschaffen.

Bei manchen Stücken hat man verschiedene Arrangements, die dann auch aus verschiedenen Quellen stammen. In diesem Fall ist fast alles gleich, nur eben die Quelle nicht.

Für eine Quelle sollten die üblichen Metadaten (z.b. Dublin Core) angegeben werden. Ich vermute man braucht sogar eine eigene Tabelle dafür.

Beim Stück selbst muss man dann auf die Quelle (z.B. ein Notenbuch) verweisen und eine Feld für Referenz in der Quelle haben (z.b. die Nummer im Notenbuch).

Daher schlage ich vor, das Quellenmanagement fest in die Datenbank einzubauen. Der Wunsch nach benutzerdefinierten Feldern bleibt natürlich.

**Comment by mattimaier** [comment]
Die Anforderungen sind für das Repertoire so nun umsetzbar:
![2019-02-03_11h43_37](https://user-images.githubusercontent.com/1818429/52175760-f894c880-27a8-11e9-93f3-296b7399a5c2.png)
