### ISSUE TITLE
tatsächliche Probenteilnahme verwalten

### ISSUE THREAD

**Issue by xalbrecht** [mattimaier/bnote#326]
Zur Zeit kann man sehr gut eine Probe planen. Da es vorkommen kann, dass manche Teilnehmer trotz Zusage nicht erscheinen, würde ich nach einer Probe gerne die tatsächliche Teilnahme erfassen. 
Im Nachgang auch eine Auswertung über den Probenbesuch mit frei wählbarem Probenzeitraum

**Comment by mattimaier** [comment]
Bei der Implementierung bin ich mir leider nicht ganz sicher ob ich das so richtig hinbekommen habe. Das muss man ordentlich testen vor dem Release.

**Comment by xalbrecht** [comment]
Vielen Dank,

ich versuche das zu testen. Komme aber erst im November dazu.

Von meinem iPhone gesendet

**Comment by xalbrecht** [comment]
Hallo

ich habe es endlich getestet. Ist aus meiner Sicht gut geworden. Ich kann die "Teilnahme bearbeiten".

folgende Anregungen:
- Status "zugesagt" = Häkchen von einem Status "hat teilgenommen" z.B. = doppeltes Häkchen bei der Bearbeitung ermöglichen
- bei vergangenen Proben die Spalte "nimmt teil" in "hat teilgenommen" ändern oder 2 Spalten anzeigen für "Zusage" und "tatsächliche Teilnahme"

**Comment by mattimaier** [comment]
@xalbrecht Finde deine Anregung gut. Leider ist das ziemlich viel Aufwand, weil aktuell nur 1 Zustand je Teilnehmer und Probe/Auftritt gespeichert wird. Würde man das jetzt um Korrekturen erweitern müsste man das Datenmodell ändern und das wäre das schwierig mit einem Update. Ich schlage daher vor, dass wir ein neues Ticket erstellen mit diesem Vorschlag und das dann ggf. später einbauen.
