### ISSUE TITLE
BNote-App Repertoire-Liste hängt

### ISSUE THREAD

**Issue by xalbrecht** [mattimaier/bnote#327]
Ich habe ein Repertoire von ca. 850 Liedern eingepflegt. In der BNote-App bleibt die Repertoireliste bei Buchstabe "D" hängen. Ein Scrollen nach unten ist nicht mehr möglich.

**Comment by mattimaier** [comment]
Add pagination to app (for repertoire only)

**Comment by mattimaier** [comment]
Habe es nun mit >500 Titeln versucht. Wenn man es ins Suchfeld tippt, dann findet das System die Songs. Die Model-maxSize zu erhöhen ist nicht hilfreich, weil es dann noch langsamer wird. Daher *won't do*.
