### ISSUE TITLE
Repertoire - Liste drucken/exportieren

### ISSUE THREAD

**Issue by xalbrecht** [mattimaier/bnote#328]
-  es wäre schön, wenn das Repertoire gedruckt/exportiert werden könnte
ggf. gefiltert/sortiert nach Genre/Titel o.ä

**Comment by bwl21** [comment]
m.e. genügt hier ein Export nach Excel. Oder aber ein generischer Report-generator.

**Comment by mattimaier** [comment]
Benutzerdefinierte Felder fehlen
