### ISSUE TITLE
Share-Modul iOS Berechtigung

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#332]
Unter dem mobilen iOS Browser ist es nicht möglich das Share-Modul zu benutzen, da immer eine Fehlermeldung kommt, dass der jeweilige Nutzer keine Berechtigung für das Modul hat.

**Comment by mattimaier** [comment]
Das Problem liegt an den Links im Frame und wie iOS damit umgeht.
Referenz: https://www.12live.de/de/blog/javascript/ipad-stay-in-webapp-fullscreen-when-links-in-embedded-iframe-are-clicked/
