### ISSUE TITLE
E-Mail Empfänger

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#338]
Es wäre hilfreich, wenn in der Mail steht an welche Gruppe bzw. Gruppen die Mail gerichtet ist. Aktuell weiß man als Empfänger nicht an wen die Mail gerichtet ist.

**Comment by mattimaier** [comment]
Welche E-Mail-Funktion soll deiner Meinung nach wo den Namen der Empfängergruppen enthalten? Im Betreff finde ich es unpassend, da viele kleine Gruppen nur eine Gruppe haben und es daher unpraktisch ist (z.B. wenn da "Mitglieder:" im Betreff steht). Für größere Ensembles mit mehreren Gruppen könnte das allerdings Sinn machen.

**Comment by HenningKuehl** [comment]
Ich würde es eventuell als optionales Feature einbauen. Beim Schreiben einer Mitteilung könnte es die Möglichkeit geben ein Häkchen zu setzen, um die Empfänger mit in die Mail zu schreiben.
Die Empfänger müssten nicht unbedingt in den Betreff sondern könnten vielleicht als Untertitel angezeigt werden.

**Comment by bwl21** [comment]
man könnte es ja in den displayNamen des Empfängers reinschreiben. 

z.B. Matti Maier [bnote entwickler]
