### ISSUE TITLE
Repertoire: Sonderzeichen in Titel

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#340]
Anfrage:
_Wollte gerade den Titel "Can't stop this feeling" anlegen, das hat erst geklappt, als ich den Apostoph bei
"can't" weggelassen habe ..._

Referenzen:
#95 wurde das Problem schonmal diskutiert.

Prüfen ob das Problem in 3.4 wieder besteht und ob die En- und Dekodierung noch geht.

**Comment by mattimaier** [comment]
Dieses Feature habe ich jetzt in 3 verschiedenen (neu + upgraded) Systemen (alle 3.4.0) versucht und 3x mit Erfolg konnte ich den Titel hinzufügen.

**Comment by ULinn** [comment]
Die Ursache für den Fehler war in der Tat nicht das Sonderzeichen, sondern der fehlende Komponist, siehe #348 
Sorry, für die falsche Fährte ...
