### ISSUE TITLE
Repertoire: Besetzung und Länge importieren

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#341]
Beim Import von Songs ins Repertoire sollte die Länge und die Besetzung mit importiert werden können.

**Comment by ULinn** [comment]
Ich habe den commit getestet, der Import hat funktioniert, allerdings wurden noch immer keine importierten Titel angezegit. Der Grund ist das fehlende Genre. Wird ein Genre festgelegt, werden alle Artikel angezeigt. Lösungsvorschlag: Möglichkeit beim Import einen Defaultwert für das Genre ("N/A") festzulegen.
