### ISSUE TITLE
Anzeige Kontaktdaten unter Mitglieder konfigurieren

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#343]
Aus Gründen des Datenschutzes sollten den Mitgliedern - vor allem bei größern Chören / Orchestern - nicht einfach alle Kontaktdaten der anderen Mitglieder angezeigt werden. Der Vorstand / Bandleader / Dirigent o.ä. braucht Zugriff auf alle Daten, aber jedes Mitglied muss selbst entscheiden können, ob seine Daten den anderen angezeigt werden oder nicht - idealerweise sogar, welche Daten.

Einfache Lösung: Damit die eigenen Daten angezeigt werden, muss man bei den Kontaktdaten ein Häckchen bei "Daten anderen Mitgliedern zeigen" setzen. Wenn das nicht gesetzt ist, werden die Daten nur dem Admin o.ä. angezeigt. 

Aufwändigere Lösung: Bei jedem einzelnen Feld in den Kontaktdaten gibt es ein solches Häkchen.

**Comment by mattimaier** [comment]
Jeder Benutzer kann nun diese Optionen einstellen:
![2022-04-04_14h31_46](https://user-images.githubusercontent.com/1818429/161544259-a9baa072-7e45-4733-96aa-67103b0d48ce.png)
Die E-Mail-Adresse wird für die Anmeldung und fürs Mailing benötigt, daher habe ich diese nicht explizit aufgeführt. Stellt man einen Haken ab, werden diese Felder nur noch für Admins sichtbar angezeigt. Außerdem kann ja auch jedes Mitglied eigentlich entscheiden, was er da reinschreibt.

**Comment by mattimaier** [comment]
Mitglieder werden aktuell gerade irgendwie nicht angezeigt - Fehler?

**Comment by mattimaier** [comment]
Konfigurationsfehler eigentlich nur - geht und die Kontaktdaten werden entsprechend der Konfiguration einschränkt wiedergegeben.

**Comment by ULinn** [comment]
Bei mir erfolgt auch keine Anzeige - obwohl Mitglieder Daten freigegeben haben. Was muss da in der Konfiguration geändert werden?

Und noch eine Anregung - auch wenn sie etwas spät kommt: Auch die Anzeige der E-Mail-Adresse sollte für andere Nutzer freigegeben oder gesperrt werden können. Klar ist sie für BNote erforderlich, aber das hat nix damit zu tun, ob andere sie zur direkten Kontaktaufnahme sehen dürfen oder nicht.

**Comment by mattimaier** [comment]
Jetzt habe ich nochmal an vielen Stellen nachgeschärft und die E-Mail-Adressenanzeige auch beschränkt. Bitte prüfen, ob jemand noch in irgendwelchen Tabellen Fehler bekommt.
Kontakte werden in `Mitglieder` angezeigt, wenn sie entweder in der gleichen Gruppe sind oder mindestens eine Probenphase teilen. Die habe ich lokal überprüft und das scheint zu funktionieren.

**Comment by ULinn** [comment]
Bei mir werden im Menüpunkt Mitglieder keine Mitglieder angezeigt (mein Benutzer ist Admin, aber auch Mitglied in zwei Gruppen mit vielen Mitgliedern).

**Comment by ULinn** [comment]
Kann mit "normalem" Testnutzer gerade nicht test, siehe #473

**Comment by mattimaier** [comment]
Ich glaube da war noch ein Join-Problem drin, bitte folgende beiden Dateien mit aktuellem Stand im Repo aktualisieren:
`BNote/src/data/systemdata.php`
`BNote/src/data/modules/mitspielerdata.php`
