### ISSUE TITLE
Teilnehmerübersicht sortieren

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#344]
Für die Übersichtlichkeit wäre es sinnvoll, wenn auch die Teilnehmerübersicht nach Stimmen sortiert werden könnte.

**Comment by mattimaier** [comment]
@ULinn Auf welcher Maske bzw. in welchem Modul? Teilnehmer gibt es an vielen Ecken ;-)

**Comment by ULinn** [comment]
Prinzipiell überall, wo Mitgliederdaten angezeigt werden. Konkret meinte ich aber den Button "Teilnehmerübersicht" im Modul "Proben" (/BNote/main.php?mod=5&mode=overview)

**Comment by hermannluehrs** [comment]
Sortierbarkeit der Mitgliederdaten auch in der Übersicht „Mitglieder“, die usern mit der Berechtigung „Mitglieder“ gezeigt wird. Am besten durch user selbst, wenn die Seite aufgerufen wird. In dem Fall gern so, dass auch nach unterschiedlichen Merkmalen sortiert werden kann: Nachname, Stimme, Geburtstag, PLZ/ Ort

**Comment by hermannluehrs** [comment]
OK. Dann bleibt /BNote/main.php?mod=13 so.

**Comment by mattimaier** [comment]
@hermannluehrs @ULinn Habt ihr das Ticket getestet und funktioniert es? Wenn ja, dann kann ich das Ticket abschließen.

**Comment by hermannluehrs** [comment]
ich kann derzeit nicht testen, weil die installation auf strato mit alpha2 nicht durchläuft. 

Am 01.04.2022 um 13:04 schrieb Matti Maier ***@***.***>:

﻿
@hermannluehrs @ULinn Habt ihr das Ticket getestet und funktioniert es? Wenn ja, dann kann ich das Ticket abschließen.

**Comment by ULinn** [comment]
Beim Menüpunkt Proben / Detailanzeige / Teilnehmer wird die Übersicht "Instrumente" (siehe Screenshot) alphabetisch sortiert, daran kann ich nichts ändern, das ist aus meiner Sicht auch nicht notwendig.
Weiter unten bei den erhaltenen Zu- / Absagen fehlt die Stimme in der Liste, daher kann danach nicht sortiert werden. Wäre aber "nice to have".
Bei den "Ausstehenden Zu- / Absagen" wird das Instrument angezeigt und die Sortierung funktioniert wie gewünscht.
Die in #345 beschriebene Sortierung habe ich noch nicht getestet, näheres dort.

**Comment by ULinn** [comment]
Die letzten Kommentare bezogen sich auf die alphabetische Sortierung VOR Anpassung der Reihenfolge lt #345 
Die Sortierung nach Instrument sollte in allen Listen einheitlich erfolgen.

**Comment by mattimaier** [comment]
@hermannluehrs BNote alpha 3 ist online:
[BNote 4.0.0 alpha 3](https://github.com/mattimaier/bnote/blob/master/BNote-Releases/BNote/Major/bnote_release-400_alpha3.zip)

**Comment by mattimaier** [comment]
Um BNote 4.0.0 abzuschließen, werde ich dieses Issue nach 1 Monat ohne Aktivität schließen. Sollte es hier zu Problemen kommen, bitte ich um ein neues Issue. Version 4.0.1 öffne ich nach dem 4.0.0 Release.
