### ISSUE TITLE
Sortierung Instrumente festlegen

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#345]
Die Festlegung einer Sortierung der Instrumente wäre sinnvoll. 
Beispiel Chor: Sopran > Alt > Tenor > Bass
statt alphabetisch: Alt > Bass > Sopran > Tenor
Oder im Orchester nach Holz / Blech / etc.

Je mehr Instrumente / Stimmen, desto wichtiger. 

Das lässt sich notdürftig durch eine Nummer am Anfang des Instrumenten-Namen lösen: 
"01 Sopran" > "02 Alt" > "03 Tenor" > "04 Bass".

Daher keine hohe Dringlichkeit.

Siehe auch #306, #344

**Comment by mattimaier** [comment]
Technisch könnte man einen Sortierindex in die Instrumententabelle machen und diese default-mäßig vergeben und in der Konfiguration editieren lassen.

**Comment by ULinn** [comment]
Genau sowas meinte ich.

**Comment by ULinn** [comment]
Ich finde in 4.0 die Konfiguration der Instrumente nicht mehr, wo kann ich das testen?

**Comment by mattimaier** [comment]
Bitte oben auf das Zahnrad gehen und dann links im Menü auf Konfiguration > Instrumente

**Comment by ULinn** [comment]
Da alles andere in der Parameter-Liste auftaucht, hatte ich die Instrumente auch dort gesucht ... Feedback kommt gleich.

**Comment by ULinn** [comment]
Ich kann die Reihenfolge in der Instrumentenkonfiguration angeben und dort danach sortieren: Funktioniert.
Dir dort gemachten Eingaben haben aber keine Auswirkungen auf die Sortierung unter Proben / Details / Teilnehmer, dort wird nach wie vor alphabetisch nach Instrumentennamen sortiert. Auch bei den ausstehenden Zu-/Absagen erfolgt die Sortierung beim Klick auf den Spaltenkopf nach Alphabet.

**Comment by ULinn** [comment]
![chrome_2022-04-01_14-07-37](https://user-images.githubusercontent.com/1461623/161260456-30c28254-83c2-44eb-ad74-cc454de76939.png)
![2022-04-01_13-26-56](https://user-images.githubusercontent.com/1461623/161260468-78a8fef2-7cf3-4e74-b56b-43832603f89b.png)

**Comment by mattimaier** [comment]
Die Implementierung muss noch von mir getestet werden, aber da fehlt in der Tat noch was.

**Comment by mattimaier** [comment]
Mit diesem Fix sollte es nun tun:
![2022-04-03_13h16_28](https://user-images.githubusercontent.com/1818429/161425207-86f6b7de-0109-4512-a958-aea7ae93c412.png)

**Comment by ULinn** [comment]
Fix funktioniert, die Ansicht unter "Instrumente" ist nun korrekt sortiert. Prima.
Wenn ich weiter unten die Listen der erhaltenen bzw. ausstehenden Zu-/Absagen per Klick auf den Spaltenkopf nach Instrument sortieren will, wird allerdings dort weiterhin nach Alphabet sortiert.

**Comment by ULinn** [comment]
Auf der Startseite / Dashboard wird auch eine Teilnehmerübersicht angezeigt, auch dort wird die Sortierung nicht berücksichtigt:

![2022-04-05_13-56-45](https://user-images.githubusercontent.com/1461623/161749078-63453bec-6c71-4e60-8f33-38b9e1f906f2.png)

**Comment by mattimaier** [comment]
> Fix funktioniert, die Ansicht unter "Instrumente" ist nun korrekt sortiert. Prima. Wenn ich weiter unten die Listen der erhaltenen bzw. ausstehenden Zu-/Absagen per Klick auf den Spaltenkopf nach Instrument sortieren will, wird allerdings dort weiterhin nach Alphabet sortiert.

Das Problem ist, dass die aktuelle Version der `datatables` Tabellen keine andere Sortierindices unterstützen. Man könnte nur den Sortierindex präfixen, das sieht aber doof aus.

Auf der Startseite habe ich den Query umgebaut. Kann man mit alpha 4 testen...

**Comment by ULinn** [comment]
Kann das gerade nicht testen, weil es bei mir wegen Osterpause noch keine Einträge für zukünftige Proben gibt, nur für zukünftige Termine, aber da werden auf der Startseite keine Teilnehmer angezeigt.

**Comment by mattimaier** [comment]
Bitte 4.0.1 issue aufmachen, wenn hier was noch nicht passt
