### ISSUE TITLE
Komponist / Arrangeur nicht erforderlich

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#348]
Bei der Neuanlage eines Titels ist nur "Titel" mit * als notwendig gekennzeichnet. Wird jedoch kein Komponist / Arrangeur angegeben, erscheint die - irreführende - Fehlermeldung:
"Fehler: Ein oder mehrere Felder enthalten ungültige Werte. (subject / )"
Lösungsmöglichkeit 1 (favorisiert): Songanlage ohne Komponisten ermöglichen
Lösungsmöglichkeit 2: Komponist mit "*" als Pflichtfeld kennzeichnen
Lösungsmöglichkeit 3: Fehlermeldung, die konkret auf das fehlende Feld hinweist.

**Comment by mattimaier** [comment]
*Test*
Wenn Arrangeuer/Komponist nicht gesetzt > Bearbeiten und einen setzen > wird nicht gespeichert
