### ISSUE TITLE
Zugriff auf Programm-Details (Titel-Liste) für Mitglieder

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#349]
Wenn ich ein Konzertprogramm anlege, wird bei den Mitgliedern in der Veranstaltung nur der Name des Programms angezeigt, aber nicht die Titel, die zum Programm gehören. Dabei wäre es wichtig, dass die
Mitglieder wissen, welche Stücke sie vorbereiten sollen.

Wenn ich das Modul Konzerte / Auftritte für die Mitglieder freigebe, können diese Auftritte und Programme ändern, das sollen sie aber nicht.

Vorschläge:
1.) Programmname bei Veranstaltungen mit Verlinkung auf eine Anzeige der jeweiligen Titelliste
2.) Anpassung des Moduls "Konzerte / Auftritte", so dass Mitglieder nur Lese-Status haben, und Administratoren ändern können. Alternativ: Unterbringung der Programmanzeige in einem anderen Modul.

**Comment by mattimaier** [comment]
Auf der Startseite wurde nun das Programm zum Auftrittsdetail hinzugefügt
