### ISSUE TITLE
Finanzen: Keine Buchung ohne Steuer / Fehlermeldung falsch

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#351]
Wenn ich im Modul "Finanzen" eine neue Buchung anlege, und das Feld "Steuer" leer lasse (ist nicht als Pflichtfeld gekennzeichnet), kommt die irreführende Fehlermeldung "Fehler Betrag nicht erkannt.". Trage ich "0" oder einen anderen Wert bei Steuer ein, wird die Buchung akzeptiert.

Hier sollte ein leeres Feld als "0" interpretiert werden.

Außerdem wäre es sinnvoll, klar zu kennzeichnen, ob in das Feld "Steuer" ein absoluter Betrag oder ein Prozentsatz eingetragen werden soll (und beim Prozentsatz, ob 19% als "0,19" oder "19" angegeben werden sollen.

**Comment by mattimaier** [comment]
Mit dieser Implementierung habe ich gleich für mehrere Entitäten mit Geldbezug die Felder aktualisiert. Außerdem ist nun eine Option zur Währungskonfiguration drin.
