### ISSUE TITLE
Kontakt Pflichtfelder

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#353]
Wenn ich als Admin einen neuen Kontakt anlege, reicht Name und E-Mail. Wenn der Benutzer dann seine Kontaktdaten ändern / anpassen will, scheint "City" ein Pflichtfeld zu sein, ein Speichern ohne Angabe des Ortes ist nicht möglich.
Vorschlag 1: Nur die für die Funktion notwendigen Felder sollten Pflichtfelder sein. 
Vorschlag 2: Alle Pflichfelder sollten entsprechend gekennzeichnet sein

**Comment by mattimaier** [comment]
In Ticket #357 gelöst
