### ISSUE TITLE
Anführungszeichen im Feld "Anmerkungen" bei Songs führen zu SQL-Fehler

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#354]
Wird im Modul Repertoire bei "Song bearbeiten" im Feld "Anmerkungen" ein Anführungszeichen verwendet, wird ein SQL-Fehler ausgeworfen:

`Fehler
The database query has failed:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Rock im Chor 3"", is_active = 1, composer = "13" WHERE id = 1143' at line 1.
Debug:UPDATE song SET title = "IT's my Life", length = "00:03:33", genre = 5, bpm = 120, music_key = "c#m", status = 2, setting = "SATB", notes = "Im Heft "Rock im Chor 3"", is_active = 1, composer = "13" WHERE id = 1143`

**Comment by mattimaier** [comment]
Problem ist nun hoffentlich behoben durch besseres encoding und decoding der Titel und Anmerkungen
