### ISSUE TITLE
Modulauswahl für BNote App

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#356]
Die Möglichkeit, den Mitgliedern einzelne Module zuzuordnen (oder eben nicht) im Hauptprogramm ist sehr gut. Wichtig wäre es, wenn das auch für die App funktionieren würde.

Konkret: Wegen DSGVO habe ich das Mitglieder-Modul nicht zugewiesen, weil sonst jeder alle Kontaktdaten sehen kann. In der App werden aber dennoch alle Daten angezeigt.

**Comment by mattimaier** [comment]
Die webapp wird nicht mehr wirklich weiterentwickelt, da wir auf ein responsives UI umstellen wollen (Entwicklung läuft bereits). Daher habe ich jetzt einfach nur die Mitspieler-Daten im Interface deaktiviert, wenn der Benutzer keine Berechtigungen auf das Modul hat.
