### ISSUE TITLE
Bug: Kontakt bearbeiten

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#357]
Beim Bearbeiten eines Kontaktes kommt nach dem Speichern folgende Fehlermeldung:

> Fehler
>> Ein oder mehrere Felder enthalten ungültige Werte. (city / )

Dies passiert natürlich nur, wenn man das Feld "Stadt" leer lässt.

**Comment by mattimaier** [comment]
Pflichtfelder im Formular "Kontakt hinzufügen" anzeigen

**Comment by HenningKuehl** [comment]
Aus welchem Grund wurde das Feld "Stadt" denn nun als Pflichtfeld markiert?

**Comment by mattimaier** [comment]
Weil ich ein Feld der Adresse braucht, sonst macht die Struktur leider keinen Sinn und es viel komplizierter die Adressen zu verwalten. Außerdem weiß man normalerweise schon aus welcher Stadt/aus welchem Ort die Person ist.
