### ISSUE TITLE
Kalender Export: Fehlende Termine

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#358]
Im exportierten Kalender werden "normale" Termine, die man in den Kalender einträgt, nicht mit aufgenommen.

**Comment by mattimaier** [comment]
Dieses Problem kann ich in 3.4.1 nicht nachstellen

**Comment by HenningKuehl** [comment]
Okay, da hat sich dann wohl ein Fehler meinerseits eingeschlichen.
Bei mir klappt es nun auch.
