### ISSUE TITLE
B-Note Umlaute mit PHP 7.2 oder 7.3 fehlerhaft auch in 3.4.1

### ISSUE THREAD

**Issue by twobnt** [mattimaier/bnote#359]
Hallo,
herzlichen Dank für euer tolles Tool :+1:

Folgendes ist mir in der Version 3.4.1 und auch schon in der 3.3x aufgefallen, 

Sofern ich B-Note mit PHP 5.6 betreibe, sind die Umlaute in Ordnung

Betreibe ich ich B-Note mit PHP 7.2 oder 7.3 werden alle Umlaute des eigenen Contents falsch angezeigt.
Ist reproduzierbar sucht umschalten der PHP-Version.

![B-Note Umlaut falsch 7 2](https://user-images.githubusercontent.com/48627455/54478461-b54f6000-4812-11e9-9815-f9af9475936e.jpg)
![B-Note Umlaut falsch 7 2](https://user-images.githubusercontent.com/48627455/54478463-b84a5080-4812-11e9-8790-859b7ceadd9d.jpg)

Grüße

**Comment by mattimaier** [comment]
@twobnt das scheint mir ein Problem beim Upgrade von PHP 5.x auf 7.x zu sein. Habe soeben auf 7.2 versucht das Problem nachzustellen und komme nicht weiter. Idee wie man das machen könnte?

**Comment by twobnt** [comment]
Hallo Matti,

Ja, ist definitiv mit der PHP-Umstellung gekommen.
Gehe davon aus, dass Du das Problem nachstellen ?

Ich hätte folgenden Idee:

Suche in der Datenbank die Zeichen und ändere alle Einträge händisch. Dauert ca 1,5h
Da ich weiß, was ich da in der DB tue,... kein Thema. Nur habe ich keine Lust dies mehrfach zu tun :-). Und was machen die User, die selbst nicht in der DB korrigieren können.
Dafür bin ich leider zu wenig DB Entwickler.

Kann aber gerne mit verproben und testen :-D

**Comment by mattimaier** [comment]
Das ist natürlich keine Lösung - klar. Auf welches Charset ist deine Datenbank eingestellt? Im BNote Installationsskript steht eigentlich immer `CHARSET=utf8` ... das ist ja dann unabhängig von der PHP Version. Jetzt habe ich noch eine Idee - versuche mal folgende Zeile in `src/data/database.php` als letzte Zeile des Konstruktors einzufügen:
![2019-08-12_19h47_51](https://user-images.githubusercontent.com/1818429/62885938-5c8ce080-bd3a-11e9-8d58-7fb5d180a90a.png)
Alternativ, versuche mal dieses Encoding:
`mysqli_set_charset($this->db, "iso8859-1");`

Wenn eines der beiden Encodings dein Problem behebt, dann kann ich das als Konfiguration einbauen und ins Admin-Wiki aufnehmen.

**Comment by twobnt** [comment]
Hallo Matti,

Also die DB ist utf8. Und ich haben die beiden Möglichkeiten von Dir verprobt.

Diese Einstellung:
		mysqli_set_charset($this->db, "iso8859-1");
		oder
		mysqli_set_charset($this->db, "utf8");

Zeigt unter PHP7.2 keinerlei Wirkung. Unter PHP5.6 sehr wohl.




Nach dem ich den "Fehler" bei Dir gemeldet habe, sind ja bereits neue Einträge im B-Note entstanden.
Diese neuen Einträge werden richtig  angezeigt. In der DB steht ein "ü" und im Webinterface wird ein "ü" angezeigt

Die alten B-Note Einträge (Vor der Umstellung auf PHP7.2) werden in der DB als  "Ã¼" geführt und nun genau so in der GUI als "Ã¼" angezeigt.

Hier ist das Problem der Zeichensätzte beschrieben.
https://php-de.github.io/jumpto/utf-8/
Du wirst dies kennen.

Ich vermute, das der "Fehler" nicht erst beim Auslesen kommt, sondern schon beim Schreiben in die DB passiert ist. Oder bereits bei der ersten Installation und Einrichtung der DB unter damals noch PHP5.6

Wie komme ich zu dieser kühnen Behauptung: Du hast in der Installation bereits Instrumente angelegt, hier stehen in der DB bei mir auch "FlÃ¶te" und nicht "Flöte" drin.


Folgendes ist Fakt:

In der DB Steht nun gemischt "ü" und "Ã¼" (natürlich für alle anderen "Sonderzeichen" auch) drin, also im Prinziep beide Zeichensätzte bund gemischt. Das die GUI hiermit bei der Darstellung nicht klarkommt,… ist auch klar.

Warum das nun so passiert ist ist unklar, (Fehler bei meiner DB Installation, Fehler bei der installation von B-Note, oder inkompatibilitäten von PHP). Solange das nur mich betrifft,.. :-) werde ich dies nun in der DB händisch bereinigen. Das ist zwar unsexy aber wird funktionieren.

Grüße Stefan

**Comment by twobnt** [comment]
Ich danke Dir für Dein Unterstützung :-) Stefan

**Comment by mattimaier** [comment]
Danke für deine Antwort. In BNote wurde auch der MySQL-Treiber von ein paar Versionen auf mysqli umgestellt - das könnte sicher auch was damit zu tun haben. Sorry, dass du dir die Arbeit machen musst...

**Comment by twobnt** [comment]
Hi Matti,
Du kein Thema. Ich bin ja froh, dass Du mehr Zeit investiert als Ich ;-)
