### ISSUE TITLE
Downloadprobleme *.mp3 Fehlermeldungen php

### ISSUE THREAD

**Issue by twobnt** [mattimaier/bnote#360]
Hallo,

hier noch ein weiteres Problem, ich weiß nicht ob es sich um eins oder gar mehrere Probleme handelt.

Auslöser sind *.mp3 Files die mit einem IE der Version 11.0.96.19301 (Win7) oder bestimmten Safari Versionen zu Timeouts führen

ein aktueller FF65.0.2 oder IE 11.648.17134.0 hat hier keine Schierigkeiten

Nachfolgende Fehler finden sich im php Log der Webseite.

[Sat Mar 16 16:20:07.775949 2019] [fcgid:warn] [pid 32608] [client 001.001.001.001:64089] mod_fcgid: stderr: PHP Warning:  Invalid argument supplied for foreach() in /var/www/clients/client21/web67/web/b-note/BNote/src/presentation/widgets/dataview.php on line 127, referer: https://webside.de/b-note/BNote/main.php?mod=1

[Sat Mar 16 16:24:52.860619 2019] [fcgid:warn] [pid 32606] (32)Broken pipe: [client 001.001.001.001:50017] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function, referer: https://webside.de/b-note/BNote/main.php?mod=12&fbfunc=view&path=groups%2Fgroup_13%2F

[Sat Mar 16 16:28:47.483086 2019] [fcgid:warn] [pid 32699] (70007)The timeout specified has expired: [client 001.001.001.001:64367] mod_fcgid: ap_pass_brigadefailed in handle_request_ipc function, referer: https://webside.de/b-note/BNote/main.php?mod=12&fbfunc=view&path=data%2Fshare%2Fgroups%2Fgroup_13%2F

[Sat Mar 16 16:37:06.556789 2019] [:error] [pid 5562] [client 001.001.001.001:49171] FastCGI: server "/var/www/clients/client21/web67/cgi-bin/php-fcgi-*-443-webside.de" stderr: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/clients/client21/web67/web/b-note/BNote/src/presentation/widgets/dataview.php on line 127, referer: https://webside.de/b-note/BNote/main.php?mod=12&fbfunc=view&path=groups%2Fgroup_13%2F

dieser Fehler ist unabhänging der eingesetzten PHP Version und des genutzen Modus

Auf der Webseite in IE 11.0.96.19301 (Win7) erschein dann folgenden Meldung
![Timeouts](https://user-images.githubusercontent.com/48627455/54478628-9b168180-4814-11e9-8ccb-adf5cd746257.jpg)

Grüße

**Comment by mattimaier** [comment]
Die Fehlermeldung hat auf etwas anderen hingedeutet (Fehler im Dataview, den ich hier behoben habe). Das eigentliche Problem (mp3 wird nicht abgespielt) kann ich allerdings auf meinen Systemen nicht nachstellen.

**Comment by twobnt** [comment]
Hallo Matti,

Werde Deine Korrektur gerne mit der nächsten Version verproben. Danke Dir schon einmal vorab :-)
