### ISSUE TITLE
B-Note App Home und Kontakte bleiben leer

### ISSUE THREAD

**Issue by twobnt** [mattimaier/bnote#361]
Hallo zum dritten heute :-)
macht aber nix, Ich kann leider gar nicht programieren, so dass,... ich froh bin und zu würdigen weiß wenn es ein anderer macht ;-)

Die APP zeigt sowohl mit "neuem" Android und Crome als auch im I-Phone Safari (aktuellste Version) nicht alles an :-( in der Desktopversion ist alles vorhanden
![Screenshot_20190316_182155_com android chrome](https://user-images.githubusercontent.com/48627455/54479099-ccde1700-4819-11e9-9269-d325b903065d.jpg)
![Screenshot_20190316_182139_com android chrome](https://user-images.githubusercontent.com/48627455/54479100-cea7da80-4819-11e9-9199-15c01a485625.jpg)

Grüße

**Comment by Franki2018** [comment]
Das ist bei mir auch so. Als Admin sehe ich auf der app nix. Alle anderen können die Kontaktliste sehen.

**Comment by mattimaier** [comment]
Ein weiteres Problem scheint das Repertoire zu sein, das bei manchen leer ist.

**Comment by mattimaier** [comment]
Allgemeine Info:
Die WebApp möchten wir nicht mehr weiterentwickeln. Ich habe nun im Rahmen der DSGVO/GDPR Verbesserungen ein paar Restriktionen hinzugefügt, die auch die App betreffen. Allerdings sind das quasi nur notwendige Mindestanforderungen.
In der nächsten Hauptversion von BNote streben wir an, dass die Desktop-Variante responsive wird und dadurch auch auf dem Smartphone und Tablet bedienbar ist.
