### ISSUE TITLE
Registrierung kann missbraucht werden

### ISSUE THREAD

**Issue by CWBudde** [mattimaier/bnote#366]
Wir haben unsere BNote Installation frei im Netz verfügbar. Zwar haben wir den Link nirgendwo öffentlich geteilt, aber falls doch mal jemand auf die Seite kommen sollte, so ist es leicht möglich uns mit Fake-Usern zu überfluten indem man beliebig viele User über "Registrieren" erzeugt.

Wir haben den Punkt jetzt manuell erst einmal aus der loginview.php-Datei entfernt, aber unter der Oberfläche ist die Funktion natürlich weiterhin noch möglich.

Ich würde es begrüßen, wenn man mit Hinblick auf Sicherheit diese Funktion abschaltbar machen könnte, so dass wir nicht mit jedem Release die Datei von Hand bearbeiten müssen.

**Comment by mattimaier** [comment]
Es gibt die Konfigurationsmöglichkeit die Benutzerregistrierung nun auszuschalten:
![2019-11-01_16h57_18](https://user-images.githubusercontent.com/1818429/68037732-ab5a6e80-fcc8-11e9-984f-93632ac40860.png)

Ist diese Option nicht aktiv, wird die Registrierung nicht angezeigt oder wenn man versucht den Link direkt einzugeben, dann wird der Zugriff blockiert:
![2019-11-01_16h58_41](https://user-images.githubusercontent.com/1818429/68037837-de9cfd80-fcc8-11e9-8f3f-b37b9cec13ad.png)
