### ISSUE TITLE
Erstanmeldung über responsives Design

### ISSUE THREAD

**Issue by twobnt** [mattimaier/bnote#368]
Hallo,

Kann es sein, das bei der Erstanmeldung über das responsive Design via Smartphone die Abfrage zur Annahme der Datenschutzbestimmung nicht angezeigt wird.

In der Folge sieht der User nix,... kann das jemand bestätigen

Grüße

**Comment by mattimaier** [comment]
Das ist korrekt. Wir arbeiten an einer neuen Version (BNote 4) in der es nur noch 1 responsive Anwendung gibt. Aktuell sind es zwei verschiedene Anwendungen: Eine sehr abgespeckte WebApp auf Basis des SAP UI5 Frameworks und eine volle Version im Web für den Desktop (oder das große Tablet).

**Comment by mattimaier** [comment]
Es sieht so aus, als ob die Konfiguration für die Registrierung noch nicht funktioniert.
