### ISSUE TITLE
Feature Request: Proben / Auftritte verstecken / inaktiv setzen

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#370]
Wenn Proben oder Auftritte mangels Beteiligung abgesagt werden, wäre es gut, wenn man diese auf "inaktiv", "abgesagt" o.ä. setzen könnte, ohne sie löschen zu müssen. Damit bliebe die Information, wer zu- und abgesagt hatte erhalten. Außerdem gäbe es dann die Möglichkeit, den Termin doch nochmal zu aktivieren, ohne eine erneute Abfrage machen zu müssen.

Erweiterung: Noch besser wäre es, wenn man bei jedem Termin zwischen folgenden Stati wählen könnte:
geplant, zugesagt, abgesagt, versteckt
Bei "versteckt" würde nur noch der Admin den Termin sehen, bei allen anderen wird er auch den Mitgliedern gezeigt, aber mit einem Label / Farbe o.ä., die auf den ersten Blick signalisiert, wie der Status ist.

Hintergrund: Wenn es viele Termine gibt (wöchentliche Probe über viele Monate), fällt es auf den ersten Blick nicht auf, wenn ein Termin aus der Liste gelöscht wird. Wenn er aber rot hinterlegt wäre, fällt die Änderung direkt ins Auge.

**Comment by mattimaier** [comment]
Es muss eine neue Funktion geben mit Status, z.B. geplant, abgesagt, verschoben, ...

**Comment by mattimaier** [comment]
Status:
* `planned` / geplant
* `confirmed` / bestätigt
* `cancelled` / abgesagt
* `hidden` / versteckt

**Comment by ULinn** [comment]
Die Kategorien sind prima, die Unterscheidung zwischen "bestätigt" und "geplant" ist sehr hilfreich.
