### ISSUE TITLE
Repertoire-Export funktioniert nicht

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#372]
Beim Aufruf des "CSV-Export" im Modul Repertoire wird folgender Fehler angezeigt:

Diese Seite funktioniert nicht / HTTP ERROR 500

Die aufgerufene URL: https://bnote.#####.de/BNote/src/export/repertoire.csv

**Comment by mattimaier** [comment]
Was wurde genau aufgerufen? Was sagen deine Server-Logs? In meinem Testsystem ist der Export erfolgreich.

**Comment by ULinn** [comment]
Bei mir lässt sich das wie folgt reproduzieren:
Aufruf /BNote/main.php?mod=6
Klick auf "CSV-Export"
Link führt zu: /BNote/src/export/repertoire.csv

Chrome zeigt an: "Diese Seite funktioniert nicht bnote.chor-werk.de kann diese Anfrage momentan nicht verarbeiten. HTTP ERROR 500"

im access.log steht:
79.232.87.0 - - [05/Aug/2019:15:52:19 +0200] "GET /BNote/src/export/repertoire.csv HTTP/1.1" 200 3596 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" bnote.#######.de

Mit 2 verschiedenen Benutzern (Admin und Nicht-Admin) probiert, gleiches Ergebnis.

Der .csv-Export aus Auftritten / Programmen funktioniert einwandfrei.

Ich lass das nochmal von meinem Hoster gegenchecken um auszuschließen, dass dort was hängt.

**Comment by ULinn** [comment]
Folgender Fehler wird beim Hoster ausgegeben:

`[06-Aug-2019 08:22:25 Europe/Berlin] PHP Fatal error: Uncaught Error: Class 'Lang' not found in /html/BNote/BNote/src/data/data.php:56
Stack trace:
#0 /html/BNote/BNote/src/data/abstractdata.php(742): Data::convertDateFromDb('0000-00-00')
#1 /html/BNote/BNote/src/data/abstractdata.php(787): AbstractData->customFieldValueMapper(Array, Array)
#2 /html/BNote/BNote/src/data/modules/repertoiredata.php(476): AbstractData->appendCustomDataToSelection('s', Array)
#3 /html/BNote/BNote/src/export/repertoire.php(49): RepertoireData->exportData()
#4 {main} thrown in /html/BNote/BNote/src/data/data.php on line 56`

**Comment by mattimaier** [comment]
Da steht was von "CustomData", d.h. du hast deine Datenfelder nicht richtig konfiguriert oder keine Daten angegeben. Ich versuche es mal zu reproduzieren...

**Comment by ULinn** [comment]
Ich habe drei Felder beim Repertoire hinzugefügt (via /BNote/main.php?mod=17&mode=customfields, nicht von Hand):

- Fach (Ganzzahl, Freigegeben: NEIN)
- Bestand (Ganzzahl, Freigegeben: JA)
- Kaufdatum (Datum, Freigegeben: NEIN)

Nicht bei allen Stücken stehen Werte in diesen Feldern.
Hilft das?

**Comment by mattimaier** [comment]
Ich denke genau hier liegt das Problem. Er versucht das Kaufdatum einzufügen (wertlos) was in deiner Datenbank zu "0000-00-00" führt und damit zu einem ungültigen Wert. Die Fehlermeldung kommt nur nicht durch, weil das Sprachpaket hier wohl ein Problem hat. Ich nehme dies also als Bug mit folgenden Facetten auf:
* Leere CustomField Werte (ggf. nur Datum, das ist zu prüfen) führen zu Fehlern
* Die Fehlermeldung an dieser Stelle ist nicht richtig ins Internationalisierungsmodul integriert
