### ISSUE TITLE
Nachrichten mit Anhang verschicken

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#376]
Wenn ich Nachrichten im Modul Kommunikation an alle Mitglieder, Konzertteilnehmer o.ä. verschicke, würde ich gerne auch Anhänge (PDF Konzertflyer, Setlist o.ä.) mitschicken können.

**Comment by ULinn** [comment]
Funktioniert bei mir nicht. Beim Anfügen des Anhangs gibt es keine Probleme, aber die Mails enthalten keinen Anhang. Ich habe mit .jpg und .pdf getestet.

**Comment by mattimaier** [comment]
Sorry, hier war noch ein kleiner Fehler drin

**Comment by ULinn** [comment]
Jetzt funktionierts bei mir - prima!!!
