### ISSUE TITLE
Fehlermeldung bei Auftritten ohne Uhrzeit Treffpunkt

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#380]
Wenn ich einen neuen Auftritt anlege und keine Zeit für den Treffpunkt eintrage, erscheint die Meldung: "Fehler: Ein oder mehrere Felder enthalten ungültige Werte. (datetime / )"

Auftritte werden oft mit sehr viel Vorlauf angelegt, um den Termin zu blocken. Der Treffpunkt steht allerdings meist erst ein paar Wochen vorher fest - daher wäre es gut, wenn das Feld nicht ausgefüllt werden müsste.

Sollte das dennoch notwendig sein, müsste das Feld als Pflichtfeld gekennzeichnet werden und die Fehlermeldung konkreter werden.

**Comment by mattimaier** [comment]
Eigentlich wird der Treffpunkt mit der Beginn-Zeit vorbefüllt. Ändert man das natürlich bewusst, dann kommt es zu diesem "Fehler".  Jetzt wurde die Fehlermeldung allerdings grundsätzlich überarbeitet.
