### ISSUE TITLE
Proben- oder Auftrittszusagen durch Admin bearbeitbar

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#381]
Es kommt immer wieder vor, dass Mitglieder Ihre Teilnahme nicht eintragen können (kein Internet, im Urlaub, technische Probleme, Ahnungslosigkeit) und diese auf anderem Wege an den Leiter übermitteln. Für solche Fälle wäre es gut, wenn der Admin (musikalische Leiter, Gruppenleiter o.ä.) die Möglichkeit hätte, vorhandene Rückmeldungen zur Teilnahme zu ändern oder auch ganz neu einzutragen.
Diese Änderungen durch den admin sollten auch nach dem Anmeldeschluss möglich sein. Es gibt immer wieder kurzfristige Krankmeldungen etc. Wenn diese nicht nachgetragen werden, ergibt die Teilnehmerliste nach Stimmen / Instrumenten sortiert immer ein falsches Bild und es müssen "von Hand" Personen hinzu gerechnet oder abgezogen werden.

**Comment by mattimaier** [comment]
Dieses Feature wurde nun von mehreren Leuten gewünscht und wird daher in der nächsten Version umgesetzt.

**Comment by mattimaier** [comment]
Issue in current master: Saving participation in rehearsals fails
