### ISSUE TITLE
Update Dokumentation unvollständig

### ISSUE THREAD

**Issue by dnop-software** [mattimaier/bnote#385]
Vor kurzem habe ich ein Update von version 3.3.2 auf 3.4.0 eingespielt.
Als Neuling habe ich nach einer passenden Anleitung gesucht, bin aber leider nicht fündig geworden.

- Mein erster Anlaufpunkt war die Installationsanleitung auf der Wiki Seite (https://github.com/mattimaier/bnote/wiki/Installation-Guide). Dort wird auf das entsprechende .zip Archiv im Repository verwiesen
- In <Repo-Root>/BNote-Releases/BNote/Major/bnote_release-340.zip fand ich zum Einen die Release Notes, in denen aber keine Updateanleitung drin steht. Unter BNote/Reame.txt steht, dass ich einfach alle Dateien aus dem Zip-Archiv hochladen muss.
- Nachdem Update und dem ersten Einloggen in BNote bekome ich sofort eine Fehlermeldung, dass in der Datenbank eine Spalte fehlt.

-> Ein Update genau nach Anleitung funktioniert leider nicht.

Ich habe das Script update_db.php gefunden und aufgerufen. Danach hat BNote wieder funktioniert. Der Name ist selbterklärend, trotzdem möchte ich vorschlagen, einen entsprechenden Vermerk in Readme.txt zu schreiben.

**Comment by mattimaier** [comment]
Danke für den Hinweis! Ich habe nun im Wiki die Seite aktualisiert und die Release Notes auf der Releases Seite für die aktuelle Version angepasst.

**Comment by mattimaier** [comment]
Deutliche Erweiterung der Dokumentation:
https://github.com/mattimaier/bnote/wiki/H%C3%A4ufige-Fragen-(DE)
