### ISSUE TITLE
Nach Update funktioniert BNote App nicht mehr

### ISSUE THREAD

**Issue by dnop-software** [mattimaier/bnote#388]
Nach dem Update von version 1.3.2 auf 1.4.2 funktioniert die Mobilansicht BNote-App nicht mehr.

Die Login Seite erscheint noch, aber nach dem Eingeben der Logindaten geht es nicht mehr weiter.
Mit Chrome wird ein Nachrichtenfeld angezeigt: "Laden der Daten fehlgeschlagen".
Mit Firefox und Safari zeigen das Benutzerinterface an, aber oben auf der Seite steht "Keine Daten" und ein Overlay mit 3 pulsierenden Punkten wird angezeigt. In diesem Zustand bleibt die Ansicht hängen.

Das Update wurde wie folgt durchgeführt:
1. Hochladen der Dateien aus bnote_release-340.zip
2. Ausführen von update_db.php
3. Hochladen der Dateien aus bnote_patch341.zip
4. Hochladen der Dateien aus bnote_patch342.zip
5. Ausführen von update_db.php
Sollte das nicht das richtige Vorgehen zum Update sein, verweise ich auf Issue #385.

**Comment by dnop-software** [comment]
In der Web-Konsole des Firefox erscheint folgende Fehlermeldung:

SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON datasap-ui-core.js line 175 > eval:12:22
success start.controller.js:12

In dieser Zeile wird anscheinend die Funktion getAll im Backend aufregufen. Mit der Firefox Netzwerkanalyse habe ich gefunden, dass das backend offensichtlich einen Fehler zurück liefert:

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w0184b33/voices-intern.de/bnote/BNote/src/data/modules/nachrichtendata.php:1) in /www/htdocs/w0184b33/voices-intern.de/bnote/BNote/src/export/bna-json.php on line 44
Fehler

The database query has failed:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '
Warning: Cannot modify header information - headers already sent b' at line 1.
Debug:SELECT id FROM user WHERE pin =
Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w0184b33/voices-intern.de/bnote/BNote/src/data/modules/nachrichtendata.php:1) in /www/htdocs/w0184b33/voices-intern.de/bnote/BNote/src/export/bna-json.php on line 44
160500

Wahrscheinlich liegt das Problem im Nachrichtendata Modul. Tatsächlich habe ich beim Update nicht darauf geachtet, die Datei data/Nachrichten.html nicht zu überschreiben.

**Comment by mattimaier** [comment]
> Nach dem Update von version 1.3.2 auf 1.4.2 funktioniert die Mobilansicht BNote-App nicht mehr.
Ich nehme an du meinst andere Versionen, denn 1.3.2 und 1.4.2 gab es nie auf GitHub.
> ...
>    Sollte das nicht das richtige Vorgehen zum Update sein, verweise ich auf Issue #385.
Das war das richtige Vorgehen, vorausgesetzt du warst davor auf 3.3.0. Ansonsten müsste ich mir das jetzt im Detail anschauen.

Den Fehler kenne ich jetzt so noch nicht. Aber was du mal machen kannst ist die 1 leere Zeile vor dem "<?php" in der Datei srv/data/modules/nachrichtendata.php löschen. Und es dann nochmals versuchen:
https://github.com/mattimaier/bnote/blob/9dc1cd215dfb021b5b8acd3e67a9204972154d10/BNote/src/data/modules/nachrichtendata.php#L1

**Comment by mattimaier** [comment]
According to the PR of @dnop-software removing the empty line fixed the issue. PR is merged and committed.
