### ISSUE TITLE
Repertoire: Uneinheitliche Angabe von Zeiten bei Neuanlage und Bearbeitung

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#390]
Beim Neuanlegen eines Titels, wird die Zeit in Minuten verlangt, beim Ändern des Datensatzes erfolgt die Angabe in Stunden. Das führt häufig zu Fehlern.

Vorschlag: Generelle Anzeige und Eingabe in Minuten. 

Wunsch: Eingabe auch mit Komma statt : möglich, das beschleunigt die Eingabe über den Ziffernblock enorm!

**Comment by mattimaier** [comment]
Es wurde BNote intern ein neuer Datentyp "MINSEC" eingeführt, der die Anzeige vereinheitlicht und eine Eingabe als "1,5" (konvertiert in der Datenbank als 00:01:30) sowie Eingaben als 5:20 (also 00:05:20) zulässt. Die Eingabe von 65:23 ergibt 01:05:23 intern.
