### ISSUE TITLE
Benutzerdefinierte Datumsfelder können nicht gespeichert werden

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#391]
Zuschrift von Nutzer:
ich legte ein selbst-definiertes feld (eintritt_datum) für „Kontakte“ an: Anzeige- und Eingabemaske sind korrekt, doch kann die Eingabe eines Datumwertes nicht gespeichert werden (Fehlermeldung query problem). Woran liegt sowas?

**Comment by hermannluehrs** [comment]
Das Problem tritt bei allen benutzerdefinierten Feldern auf, unabhängig von Typ und Zuordnung

**Comment by mattimaier** [comment]
@hermannluehrs Leider kann ich das nirgendwo nachstellen. Auf meinen Systemen scheint es zu gehen. Kannst du bitte Screenshots von den einzelnen Schritten und die Fehlermeldung einfügen? Findest du was auf deinem Server an Fehlermeldungen? Query-Probleme werden normalerweise ausgegeben.

**Comment by hermannluehrs** [comment]
@mattimaier: hier eine reihe von screenshots, die den fehler zeigen. ich benutze die xampp-umgebung auf mac osx.
 
![7 mySql custom field date](https://user-images.githubusercontent.com/57803668/71640975-b6b02300-2c94-11ea-8b0b-f8d980275e46.jpg)

![6 custom field date](https://user-images.githubusercontent.com/57803668/71640974-b0ba4200-2c94-11ea-8216-166df55c60a3.jpg) 

![0 1 system custom field date jpg](https://user-images.githubusercontent.com/57803668/71640963-9e400880-2c94-11ea-8491-a7ef40d57f4d.jpg)
![0 2 system custom field date](https://user-images.githubusercontent.com/57803668/71640967-9f713580-2c94-11ea-8b0e-7fb0550681c1.jpg)
![1 custom field date](https://user-images.githubusercontent.com/57803668/71640968-a13af900-2c94-11ea-8019-dbbecc3d6819.jpg)
![2 custom field date](https://user-images.githubusercontent.com/57803668/71640969-a304bc80-2c94-11ea-9db6-425b78299668.jpg)
![3 custom field date](https://user-images.githubusercontent.com/57803668/71640970-a4ce8000-2c94-11ea-8f4c-b95820bf4200.jpg)
![4 custom field date](https://user-images.githubusercontent.com/57803668/71640971-a7c97080-2c94-11ea-8a38-19dee247505c.jpg)
![5 custom field date](https://user-images.githubusercontent.com/57803668/71640972-abf58e00-2c94-11ea-8d8c-b04bc24e0fc8.jpg)

**Comment by mattimaier** [comment]
Danke @hermannluehrs für die ausführlichen Screenshots. Das hat sehr geholfen. Es scheint wohl mit der Version des Datenbankservers und Treibers zu tun zu haben. Ich habe jetzt mal einen Fix vorgeschlagen. Vielleicht kannst du mir den Testen:
1. Kopiere deine aktuelle BNote/src/data/abstractdata.php Datei nach abstractdata_org.php
2. Ersetze die Datei durch diese: https://github.com/mattimaier/bnote/blob/master/BNote/src/data/abstractdata.php
3. Versuche ob du nun Speichern kannst --> wenn ja, würde ich mich über ein OK hier freuen
4. Kopiere die "kaputte" abstract_org.php wieder zurück (damit deine Version sauber ist)
5. Sobald das Update 3.4.3 da ist, kannst du es einfach installieren.

PS.: Es scheinen mir viele persönliche Daten von dir in den Screenshots zu sein (Geburtsdatum, Anschrift, etc.). Vielleicht willst du die Bilder wieder rausnehmen oder die Daten schwärzen.

**Comment by hermannluehrs** [comment]
ich habe abstractdata.php wie oben ersetzt. Fehlermeldung beim Abspeichern eines Datumwertes:
Fatal error: Uncaught Error: Undefined class constant 'MINSEC' in /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/src/data/abstractdata.php:557 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/src/data/modules/kontaktedata.php(176): AbstractData->validatePair('street', 'G\xC3\xA4rtnerstrasse...', 0) #1 /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/src/presentation/crudview.php(186): KontakteData->validate(Array) #2 /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/src/presentation/modules/kontakteview.php(412): CrudView->edit_process() #3 /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/src/logic/modules/kontaktecontroller.php(52): KontakteView->edit_process() #4 /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/desktop.php(19): KontakteController->start() #5 /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/main.php(50): include('/Applications/X...') #6 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/bnote3/BNote/src/data/abstractdata.php on line 557

**Comment by mattimaier** [comment]
@hermannluehrs Danke fürs Testen. Leider hab ich da wohl übersehen, dass es noch mehr Abhängigkeiten gibt. Also einfach wieder die alte Datei drüber und dann mit dem nächsten Update testen.
