### ISSUE TITLE
Konzertprogramm an weiteren Stellen

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#392]
Das „Programm“ eines Konzertes (Liste von Titeln aus dem Repertoire) sollte auch im Modul „Repertoire“ verfügbar/editierbar sein und auch bei Planung eines  Auftrittes.

**Comment by mattimaier** [comment]
Das sehe ich etwas anders. Im Repertoire werden eigentlich nur die Titel gepflegt. Man könnte hier vielleicht noch anzeigen in welchem Programm ein Titel ist, jedoch gehören die Programme zu den Auftritten und können dort auch verwaltet werden.
Beim Auftritt ist es aktuell noch etwas unglücklich gelöst, da bin ich bei dir, dass man hier direkt die Editierfunktionen einbetten könnte.
Bevor diese Änderungen eingebaut werden, bitte ich um Kommentare anderer Nutzer.

**Comment by ULinn** [comment]
Ich bin sehr für die Möglichkeit, das Programm direkt beim Auftritt bearbeiten zu können. Ideal wäre folgendes:
1.) Beim Anlegen eines Auftritt kann ich entweder ein Standard-Programm (aus Repertoir) hinzufügen oder ein spezielles Programm nur für diesen Auftritt "von Hand" zusammenstellen
2.) Egal, wie ich das Programm erstellt habe, muss ich es anschließend für diesen Auftritt verändern können - sowohl was die Reihenfolge angeht, also auch das Löschen und Hinzufügen von Titeln.
3.) Ideal wäre es, wenn ich aus diesem Auftritt dann später ein Standard-Programm erstellen könnte, um es für weitere Auftritte zu verwenden. 
Eine Möglichkeit, ein konkretes Auftrittsprogramm unter Repertoire zu bearbeiten, brauche ich nicht.

**Comment by mattimaier** [comment]
Umgesetzte Features:
* Auftritt erstellen: Option "Neues Programm" erzeugt ein neues Programm mit dem Titel des Auftritts
* Auftritt Details: Neue Option "Programm bearbeiten"
* Programme können als Vorlage markiert werden (auch nachträglich)
* Programm Details: Anzeige der Auftritte die das Programm verwenden mit Link um zurück zum Auftritt zu gelangen
* Programm - Titelliste bearbeiten: Einfügen aller Titel einer Vorlage
