### ISSUE TITLE
Verwendung der Docker Beispiel Dateien unklar

### ISSUE THREAD

**Issue by dnop-software** [mattimaier/bnote#396]
Mir ist nicht ganz klar, wie die Docker Dateien verwendet werden müssen.

Mit dem Kommando 'docker-compose up -d' konnte ich offensichtlich eine lokale bnote Testinstanz installieren, die im Browser über localhost erreichbar ist.

Bei der Installation der Datenbank habe ich Informationen aus docker-compose.yml eingegeben, aber danach sah ich nur eine Fehlermeldung:

Warning: mysqli_connect(): (HY000/2002): No such file or directory in /var/www/html/BNote/src/data/database.php on line 35

Fatal error: Uncaught Error: Call to a member function query() on boolean in /var/www/html/BNote/src/data/database.php:76 Stack trace: #0 /var/www/html/BNote/src/data/database.php(208): Database->exe('SHOW TABLES') #1 /var/www/html/BNote/src/data/systemdata.php(47): Database->getSelection('SHOW TABLES') #2 /var/www/html/BNote/src/logic/init.php(29): Systemdata->__construct() #3 /var/www/html/BNote/main.php(18): require_once('/var/www/html/B...') #4 {main} thrown in /var/www/html/BNote/src/data/database.php on line 76

Ein kleines HowTo wäre hilfreich, wie man mit Hilfe der Docker Dateien ein lauffähige Testinstanz aufsetzen kann.

**Comment by mattimaier** [comment]
Hier mal eine Doku dazu:
https://github.com/mattimaier/bnote/wiki/Setup-BNote-with-Docker

**Comment by dnop-software** [comment]
Danke, die Anleitung ist sehr gut verständlich

**Comment by dnop-software** [comment]
Nachdem ich lange Zeit nichts mehr mit BNote gemacht habe, habe ich völlig vergessen, wie man die Docker Container neu startet. Gut, dass es eine Anleitung gibt. Leider habe ich trotzdem zwei Tage gebraucht, bis der Container funktionierte, weil mir noch ein entscheidender Hinweis fehlte.

Bei der Installation von BNote wird ja der Name des Datenbankservers mit "localhost" vorausgefüllt, was für eine typische Webspace Installation sicherlich sinnvoll ist. Im Docker Setup funktioniert das aber nicht, weil php-apache und MariaDB in unterschiedlichen Containern laufen. Deshalb muss man bei der Installation stattdessen den Namen des MariaDB Containers eintragen (in meinem Fall "bnote-mariadb-1").

Wenn man sich mit der Funktionsweise von Docker auskennt mag das völlig selbstverständlich sein, aber für jemanden wie mich, der Docker einfach nur die vorkonfigurierten Container starten will, erschließt sich das nicht so schnell. Es wäre gut wenn ein ensprechender Hinweis zur Anleitung im Wiki hinzugefügt würde. Ich wollte das auch gleich selbst machen (ist ja ein Wiki), aber anscheinend habe ich keine Rechte Änderungen an der Seite vorzunehmen. Deswegen auf diesem Weg die Bitte, die Anleitung zu erweitern.

Mir ist auch noch ein anderes Problem aufgefallen: Wenn man den Container direkt aus der git Arbeitskopie erzeugen möchte, fehlt die Datei vendor/autoload.php. Ich habe mir damit beholfen, den ganzen vendor Ordner aus dem Release Paket in die Arbeitskopie zu übernehmen. Ich weiß aber nicht ob das der richtige Weg ist. Auch dazu wäre ein Hinweis in der Installationsanleitung hilfreich.
