### ISSUE TITLE
themes / logo in bnote app

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#398]
Ich habe in der config.datei as theme auf "red" gesetzt und ein eigenes logo platziert. Funktioniert! . Allerdings nur in der Desktopversion. Die mobile Version (bnote app) zeigt das bisherige theme (blau) unverändert an und auch das eigene logo erscheint nicht. (Meine Test-Umgebung: Mac os x / xampp als localhost). Woran liegt das?

**Comment by mattimaier** [comment]
Die mobile App wird es in Version 4 nicht mehr geben. Die ist in OpenUI5 (SAP Technologie) und wird durch eine responsive Hauptanwendung abgelöst. Dann ist dieses Thema automatisch gelöst.
