### ISSUE TITLE
Titel ohne Komponist / Arrangeur werden bei Auftritten nicht angezeigt

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#399]
Wenn ein Repertoire Titel enthält, für die kein Komponist / Arrangeur angegeben ist, werden diese zwar unter Auftritte / Programme verwalten angezeigt, nicht aber bei den über das Dashboard erreichbaren Auftritts-Infos:
/BNote/main.php?mod=1&mode=gigcard&id=8
Dort fehlen diese Titel - das sollte anders sein.

**Comment by mattimaier** [comment]
![2020-01-01_16h15_50](https://user-images.githubusercontent.com/1818429/71642827-0d782580-2cb2-11ea-93ab-26803beddc51.png)
