### ISSUE TITLE
Web App zeigt nicht alle Daten

### ISSUE THREAD

**Issue by markusroth1** [mattimaier/bnote#405]
Ich habe BNote 3.4.2 installiert und bin gerade am Testen. Bei der Web App ist mir aufgefallen, dass bei den Kontakten keine angezeigt werden obwohl ich auf dem Web Portal einige angelegt habe und diese auch dort angezeigt werden.
Ebenso wird beim Repertoire keine Daten in der Web App angezeigt. Auch hier sind im Webportal alle Stücke sichtbar.
Bei den Nachrichten passen die angezeigten Daten in der WebApp.
Als Mobil Gerät habe ich ein Smartphone mit Android. Ich habe es dort auch mit verschiedenen Web-Browsern versucht. Das Ergebnis ist dasselbe.
Ich es auch mit einem iPhone getestet. Auch hier sind keine Daten in den entsprechenden Modulen zu sehen.
Ist hier ein Konfigurationsfehler?

**Comment by mattimaier** [comment]
Mit diesem PR https://github.com/mattimaier/bnote/pull/389 sollte das Problem eigentlich gelöst sein. Ich habe jetzt noch ein paar weitere Stellen bearbeitet.
