### ISSUE TITLE
Funktion "Ordner als Zip-Archiv herunterladen" fehlerhaft

### ISSUE THREAD

**Issue by LeonardusSagittarius** [mattimaier/bnote#407]
Die Funktion "Ordner als Zip-Archiv herunterladen" macht bei uns nicht, was sie soll. Selbst wenn ein Ordner nur einige PDFs enthält, dauert es ewig bis die ZIP-Datei erstellt ist. Sie ist dann auch 1,9 GB groß (was dem gesamten Umfang unseres Share-Bereiches entsprechen dürfte). Nach etwa 845 MB meldet Firefox den Download dann als abgeschlossen. WinRar meldet beim Öffnen der entstandenen Datei dann aber ein "unerwartetes Archivende". Sie enthält entweder keine verwendbaren Dateien oder alle möglichen aus anderen Ordnern, was meinen Verdacht nährt, dass BNote den gesamten Share-Bereich zippen will.

**Comment by mattimaier** [comment]
Danke @LeonardusSagittarius für dein Feedback. Leider kann ich das Problem auf meinen Systemen nicht nachstellen. Ich vermute, dein Server packt das einfach nicht oder deine Caches sind zu klein.
Vorschlag: Lösche die Datei BNote/data/share/_temp/download.zip vom Server und versuche es erneut.

**Comment by mattimaier** [comment]
Kommentar eines anderen Nutzers:
Für folgende Webadresse wurde keine Webseite gefunden: https://.../BNote/src/data/filehandler.php?file=_temp/download.zip.
HTTP ERROR 404

**Comment by mattimaier** [comment]
#415 sollte das Problem lösen
