### ISSUE TITLE
Email Benachrichtigung bei Probe / Auftritt

### ISSUE THREAD

**Issue by markusroth1** [mattimaier/bnote#410]
Wenn ich bei BNote 3.4.3 eine Probe oder einen Auftritt anlege, erhalte ich nach dem "Speichern" eine Fehlermeldung "Benachrichtigungen können nicht angelegt werden." Die Probe oder der Auftritt wird angelegt aber es werden keine Emails an die Teilnehmer versendet. 
Die Nachrichten-Versendung im Nachhinein über den angelegten Termin funktioniert allerdings.

**Comment by mattimaier** [comment]
Das ist so eigentlich (mehr oder weniger) gewünscht:
* Legt man eine Probe an werden nicht direkt Mails verschickt, da man idR mehrere Proben anlegt und die Mitspieler nicht zuspamen möchte. Insbesondere bei der Anlage einer Probenstrecke wäre das auch sehr nervig und man würde vermutlich schnell auf einer Spammerliste landen.
* Der _Fehler_ "Benachrichtigungen können nicht angelegt werden" tritt vermutlich auf, weil die Benachrichtigung für die zeitgesteuerte Erinnerung der Teilnehmer an die Angabe der Teilnahme nicht gesetzt werden konnte. Dies geschieht über ein Online-System von BNote selbst. Du kannst das aber auf cron umstellen.
