### ISSUE TITLE
Teilnehmerübersicht der Auftritte

### ISSUE THREAD

**Issue by markusroth1** [mattimaier/bnote#411]
Für unseren Dirigenten wäre es eine super Erweiterung, wenn man (genauso wie bei den Proben) eine Teilnehmerübersicht angezeigt bekommen könnte.

**Comment by mattimaier** [comment]
@markusroth1 Kannst du das mit der BNote 4.0.0 alpha3 Version bitte testen? Hier zum [Download](https://github.com/mattimaier/bnote/blob/master/BNote-Releases/BNote/Major/bnote_release-400_alpha3.zip)

**Comment by mattimaier** [comment]
Jetzt gibt es noch eine alpha 4 Version, bitte diese verwenden.

**Comment by ULinn** [comment]
Bei mir funktioniert's.
