### ISSUE TITLE
Solist bei Stücken

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#413]
Anscheinend ist die Möglichkeit, Solisten bei Stücken festzulegen beim letzten Update verschwunden oder an eine andere Stelle verschoben worden. 
Es gibt Stücke, für die wurde in der Vergangenheit ein Solist festgelegt, dieser kann auch bei den Filtern der Repertoire-Übersicht ausgewählt werden. Wenn ich ein Stück bearbeite, gibt es dort aber kein Feld Solist (mehr).

**Comment by mattimaier** [comment]
Das scheint mir nicht so:
![2020-02-08_15h53_20](https://user-images.githubusercontent.com/1818429/74087316-334fd180-4a8b-11ea-9033-7c917a004b96.png)
