### ISSUE TITLE
Bnote-App: Benutzer-Registrierung und Aktivierung trotz Deaktivierung

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#416]
Wenn ich im Modul 'Konfigurtion' die Benutzerregistrierung und die automatische Benutzeraktivierung auf 'nein' setze, dann ist das in der Desktop-Variante auch so. Aber die Bnote-App lässt beides weiter zu.

**Comment by mattimaier** [comment]
Die Registrierung aus der App wurde auf dem Display nicht entfernt, nur es kommt dann eine Meldung, dass diese Funktion deaktiviert wurde. Hintergrund: Änderung an der Startseite der App würde die Ladezeit verlängern und das nicht nur bei der Registrierung.
