### ISSUE TITLE
Import Repertoire - Custom Fields

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#429]
Ich habe zum Repertoire ein paar custom fields hinzugefügt (Regalfach, GEMA-Nummer, Notenbestand etc.). Diese werden auch beim Export berücksichtigt. Leider stehen die Felder aber beim Import nicht zur Verfügung. 

Es wäre sehr hilfreich, wenn alle Felder (inkl. custom fields) auch beim Import berücksichtigt würden.  Dann wäre es möglich, für die Massenbearbeitung (z.B. Noteninventur) von Daten einen Export in Excel zu aktualisieren und dann wieder zu importieren - ohne jeden Datensatz einzeln aufrufen zu müssen.

Hierzu fehlt weiterhin die Zuordnung der ID im Import-Dialog - oder werden importierte Daten einfach "hinten dran gehängt" statt ggfs. vorhandene Daten zu aktualisieren?

**Comment by mattimaier** [comment]
Mit alpha 2 und einem Excel Spreadsheet der vorher exportiert wurde mit Custom Field angereichert wieder importiert. Hat für mich funktioniert.

**Comment by ULinn** [comment]
Der Export funktioniert prima, der Import allerdings nicht ganz:

Der Import der Custom-Fields funktioniert prima. Aber das Feld "Status" kann beim Import nicht korrekt zugeordnet werden (siehe Screenshot) 

![chrome_2022-04-04_14-39-33](https://user-images.githubusercontent.com/1461623/161546363-9d562971-ff75-404a-92a5-a199777e69e5.png)

Möglicherweise werden in Folge davon keine Duplikate erkannt und alle Titel ergänzt, statt aktualisiert, so dass nach dem Import jeder Titel doppelt vorhanden ist. Für eine "Erstbestückung" der Repertoire-Datenbank ist das unerheblich.

Der Workflow Export => Bearbeitung / Ergänzung in Excel => anschließender Import der aktualisierten Daten ist damit allerdings nicht möglich. 

Sollte der vorgesehen sein, wäre es eine Erleichterung, wenn beim Import der exportierten Excel-Tabelle inkl. Spaltenüberschriften die Feldzuordnung automatisch erfolgt und nur bei unklaren Bezeichnungen noch eine Auswahl getroffen werden muss. Fällt aber unter "nice to have" ...

**Comment by mattimaier** [comment]
Jetzt habe ich hier einiges geändert und getestet, bin mir aber noch nicht ganz sicher ob das ganz funktioniert. Die Logik ist:
* Beim Import werden alle Zeilen auf ID geprüft --> aktualisiere den Song
* Ist keine ID vorhanden oder die ID leer wird grundsätzlich der Song neu angelegt

Mapping von Status über Name und wenn nicht gesetzt, dann wird der zu definierende "Standard" gezogen (neue Felder)
Beim Genremapping war ein Schreibfehler drin

**Comment by ULinn** [comment]
Beim Import gibt es anscheinend noch einen Fehler bei der Song-Länge und den Komponisten.

Situation vor Export: Einige kürzlich in BNote neu angelegte Stücke haben konkrete Längen, alle anderen wurden bei der Erstinstallation mit Standardzeit 00:03:00 angelegt.

Export in CSV, Import CSV in Excel, dann Import Excel in BNote  - bei den meisten Titeln steht nun als Zeit 838:59:59 (in Liste wie Detail-Ansicht). Bei einigen wenigen Titeln steht die korrekte Zeit. 

Beim Import wurden einzelne schon vorhandene Titel neu angelegt, statt zu überschreiben - diese gibt es nun doppelt - einmal mit korrekter Zeit und einmal ohne.

In Excel sind alle Zeiten korrekt.

Bei den Komponisten stimmen einige, aber einige fehlen auch nach dem Import.

Weiterer Fehler: Nach dem Import steht bei allen Titeln "aktiv" auf "Ja"

Screenshot Repertoire vor dem Export:
![chrome_2022-04-08_16-25-00](https://user-images.githubusercontent.com/1461623/162460733-d62e491d-3f1d-48ce-bccd-a2300d6b1eca.png)

Und nach dem Import (mit Überschreiben):
![chrome_2022-04-08_16-29-56](https://user-images.githubusercontent.com/1461623/162460852-2b8c826b-4cb8-4746-9ddb-f643a7890b59.png)

Ich hatte der Excel-Liste einen Titel zu Testzwecken hinzugefügt und alle anderen unverändert gelassen. Trotzdem wurden beim Import 10 neue Titel angezeigt (siehe oben).

Ich kann die Export-Datei gerne per PM zur Verfügung stellen.

**Comment by mattimaier** [comment]
Jetzt habe ich nochmal einiges gefunden und verbessert sowie mit meinen Testdaten einiges versucht zu überprüfen.
Zum Test:
* Repertoire bitte "clean stellen"
* Export als CSV
* Umwandlung in Excel zu XSLX mit gewünschten Änderungen
* Achtung: ID Feld muss passen
* Achtung: Künstler Feld (wenn vorhandener Künstler verwendet werden soll) muss `[id=...]` enthalten
* Import XLSX > Felder angeben
* Prüfen

**Comment by ULinn** [comment]
Was bedeutet "Repertoire clean stellen"?

**Comment by ULinn** [comment]
Hat soweit alles funktioniert. Die 3 Komponistenfelder "Compsername" "Composerid" und "Composer" waren etwas verwirrend, beim ersten mal hatte ich das falsche für den Import verwendet. Mit "Composer" wurden dann aber auch die Komponisten richtig zugeordnet.

**Fehler:** Im ursprünglichen Repertoire gab es bei mir 10 Titel, die doppelt vorhanden waren (gewollt), zwar mit unterschiedlicher ID, aber sonst gleich. Beim Import wurde dann jeweils ein dritter Titel erzeugt, so dass es 10 neue Titel gibt. Ist kein Problem, muss eh in unserem Bestand bereinigt werden, ist aber wahrscheinlich so nicht gewollt.

Ein in der Excel-Tabelle geänderter Artikel wurde beim Import korrekt geupdated.

Ein in der Excel-Tabelle gelöschter Artikel wurde in BNote nicht gelöscht - für meine Arbeitsweise, bei der der komplette Bestand wieder importiert wird, wäre es besser, beim Import nicht vorhandene IDs würde gelöscht (mit Nachfrage). Wer die Import-Funktion aber nutzt, um ohne vorherigen Export regelmäßig neue Titel hinzufügen, kann damit natürlich auch einiges kaputt machen ...

**Feature Request 1:** Bei der Feldzuordnung beim Import Vorbelegung der Dropdowns, falls die Spaltenköpfe übereinstimmen. Wenn häufiger per Export- / Import aktualisiert wird, ist das jedes mal einiges an Arbeit, alle Felder zuzuordnen - mit dem Risiko, versehentlich ein Feld falsch zu belegen. 

**Feature Request 2:** Möglichkeit, Repertoire komplett zu löschen - sei es per Mehrfachauswahl oder mit einem eigenen Befehl (mit Sicherheitsabfrage). Das macht es einfach, nach fehlerhaften Importen oder einer Neuorganisation bei 0 zu starten. Die Mehrfachauswahl wäre vor allem dann wichtig, wenn eine Löschung von Titeln per Bearbeitung der Export-Tabelle nicht möglich ist (siehe oben).

**Comment by mattimaier** [comment]
Mit "clean stellen" meine ich, dass das Repertoire wieder in einem Zustand ist, den man nachvollziehen kann. Ich habe nach ein paar Mal rumprobieren festgestellt, dass der ursprüngliche Zustand mit dem ich gestartet bin zum Testen Mist war. Daher diese Anmerkung.
Außerdem habe ich ein paar Dinge implementiert nun (u.a. die _Wipe_ Funktion). Bitte mal prüfen ob jetzt besser.

**Comment by ULinn** [comment]
Neues Patch eingespielt, CSV exportiert, Excel daraus gemacht, importiert:
1.) Feldzuordnung: Einige Felder werden automatisch richtig zugordnet, bei einigen fehlt aber die Zuordnung, ohne dass ich dahinter eine Logik erkennen kann:
![chrome_2022-04-25_14-13-56](https://user-images.githubusercontent.com/1461623/165087133-fe6b1c52-2a2f-43c9-861d-17c72539e952.png)

**Comment by ULinn** [comment]
2.) Beim Import wurden wieder einige Datensätze neu erstellt, obwohl die Daten unverändert waren.

![chrome_2022-04-25_14-17-56](https://user-images.githubusercontent.com/1461623/165088004-71d7e80a-9ab8-4e44-a5f3-e393d668fad8.png)

Vorher:

![chrome_2022-04-25_14-20-12](https://user-images.githubusercontent.com/1461623/165087820-a5f33ebd-5a71-45c5-a25d-a8b23bc61a1e.png)

Nachher:

![ShareX_2022-04-25_14-19-32](https://user-images.githubusercontent.com/1461623/165087841-a11d629d-7f2d-4b27-9083-10715297ef1e.png)

(3 x "Abba" dazu gekommen)

Datenbestand Excel:

![EXCEL_2022-04-25_14-20-34](https://user-images.githubusercontent.com/1461623/165087874-e76c235a-30d9-45c7-bf17-270b5a41bb1c.png)

Anscheinend wird hier nicht (nur) die ID verwendet, sondern auch der Titel, das Problem betrifft nur Titel, die mehrfach in der Liste sind.

**Comment by ULinn** [comment]
3.) Lösch-Button

Vielen Dank für den Button.

![chrome_2022-04-25_14-24-17](https://user-images.githubusercontent.com/1461623/165088517-60061850-6fa4-422a-a7bc-525e95369a61.png)

Wenn tatsächlich alle Referenzen gelöscht werden, muss ich bei einem Neu-Einspielen des Repertoires alle Programme neu anlegen - dann macht das keinen Sinn.

Habe trotzdem testweise alles gelöscht:

![chrome_2022-04-25_14-26-25](https://user-images.githubusercontent.com/1461623/165088719-39f17c42-ae5b-4ade-8234-436c13827061.png)

Wie erwartet, kein Repertoire mehr vorhanden:

![chrome_2022-04-25_14-27-31](https://user-images.githubusercontent.com/1461623/165088862-6c43cac1-080a-431b-949f-effeb014862b.png)

Anschließend Import der unveränderten Excel-Datei:

Obwohl das Repertoire eigentlich leer sein müsste, wird die Auswahl zum Überschreiben angezeigt:

![chrome_2022-04-25_14-28-57](https://user-images.githubusercontent.com/1461623/165089124-1148c17b-4aef-4081-8cf5-a328d37498b4.png)

Anscheinend sind die alten Titel (oder IDs) doch noch irgendwo vorhanden:

![chrome_2022-04-25_14-30-03](https://user-images.githubusercontent.com/1461623/165089372-c1745eda-26f8-4ee0-873c-0b80153a804d.png)

Nun sind 9 Titel (die, die vorher auch schon "dupliziert" wurden, je 3x vorhanden, sonst wurde nichts importiert:

![chrome_2022-04-25_14-33-03](https://user-images.githubusercontent.com/1461623/165089668-ea80363a-d370-4852-b8e6-a06240d6be2b.png)

**Comment by ULinn** [comment]
3b) Nochmal Repertoire gelöscht, dann ID aus Excel-Liste entfernt, nochmal importiert:

![chrome_2022-04-25_14-38-39](https://user-images.githubusercontent.com/1461623/165090767-a0cd9f3e-c315-43c1-9eba-4acf6d3d7678.png)

Das funktioniert wie erwartet. Nun sind alle Titel im Repertoire.

**Comment by mattimaier** [comment]
Jetzt habe ich nochmal zwei Kleinigkeiten geändert und nochmals selbst mit positiven Ergebnis probiert. Hier allerdings ein paar Infos:
* Die doppelten/3-maligen Titel kann ich mir vom Code her aktuell nicht mehr erklären. Den "Titelduplettencheck" gab es mal (vor alpha 3), vielleicht passt da was vom Update her nicht.
* Wenn du IDs in den Importdaten angibst, nimmt er diese als gegeben an und prüft nicht. Ich habe Testsätze mit sehr vielen Songs, da gibt es Performance-Probleme wenn ich einzeln prüfe und Batch-weise ist die Konfiguration je nach Datenbank unterschiedlich (Parameter Size Limits). Daher habe ich das der Einfachheit wegen weggelassen und werde das auch nicht einbauen.
* Löschen erfordert das Entfernen der Referenzen, sonst hat man sehr viele Zombies in der Datenbank.
* Die Anzeige von "Überschreiben" ist als Standardoption drin und das werde ich auch so lassen.

Ich hoffe das ist nun ein akzeptabler Stand für das Release.
