### ISSUE TITLE
Terminliste Startseite: Wünsche

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#431]
Auf der Startseite werden Kalendertermine anscheinend in der Reihenfolge angezeigt, in der sie angelegt wurden, oder seh ich das falsch? Jedenfalls wünschte ich mir, 
- dass die Termine aufsteigend nach Datum angezeigt werden
- Termine vor aktuellem Tagesdatum nicht angezeigt werden
- die Anzahl der angezeigten Termine konfiguriert werden kann  
Merci!

**Comment by mattimaier** [comment]
Mit der neuen Startseite in BNote 4 hat sich Einiges verändert. Bitte neue Tickets aufmachen, die sich auf die neue Startseite beziehen.
