### ISSUE TITLE
benutzerdefinierte felder / anzeige auf MITGLIEDER 

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#435]
Ich habe benutzerdefinierte Felder (zugeordnet zu Kontakt) angelegt, mit Freigabe = ja versehen und Werte eingegeben. Auf der MITGLIEDER-Seite erscheinen die Feldnamen, aber nicht die Feldwerte. Bug?

**Comment by mattimaier** [comment]
War ein kleiner Fehler, der nur Administratoren betroffen hat.
