### ISSUE TITLE
Kalenderexport: Proben: ohne Notizen/Anmerkungen

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#437]
Der Kalenderexport übernimmt bei Proben anscheinend nicht Einträge aus "Notizen" (rehearsal . notes) und bei "Stücke zum Üben" nicht die Einträge in "Anmerkungen" (rehearsal_song . notes). Es wäre schön, wenn diese Informationen im Kalenderexport vorkommen. Merci!

**Comment by mattimaier** [comment]
In den Einstellungen muss diese Option aktiviert werden:
![2022-04-03_13h34_18](https://user-images.githubusercontent.com/1818429/161425918-1da9f898-1310-4966-a2ab-3922b5a67a1e.png)
