### ISSUE TITLE
Modul BENUTZER: Sortierfehler bei ZULETZT ANGEMELDET

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#439]
Im Modul 'BENUTZER' wird die Spalte 'ZULETZT ANGEMELDET' nicht als date/time sortiert, sondern anscheinend als char. Wohl ein bug? Wäre prima, das nach date/time sortieren zu können.

**Comment by mattimaier** [comment]
Die Tabelle sortiert nur alphanumerisch, daher bleibt mir eigentlich nichts anders als ein sortierbares Feld anzuzeigen. Ich finde das Datum ist noch lesbar und erfüllt seinen Zweck. Ist ja sowieso _nur_ eine Admin-Ansicht.

**Comment by hermannluehrs** [comment]
Hallo Matti,
ich wollte nur mal fragen: wann kommt denn das nächste Update von bnote?
Herzliche Grüße 
Hermann

Am 25.09.2020 um 21:44 schrieb Matti Maier ***@***.***>:

﻿
Die Tabelle sortiert nur alphanumerisch, daher bleibt mir eigentlich nichts anders als ein sortierbares Feld anzuzeigen. Ich finde das Datum ist noch lesbar und erfüllt seinen Zweck. Ist ja sowieso nur eine Admin-Ansicht.

**Comment by mattimaier** [comment]
So ist es sortierbar und für Admins lesbar:
![2022-04-03_13h25_20](https://user-images.githubusercontent.com/1818429/161425546-e39796ec-c912-47cd-a6c6-7cb192ccc24d.png)
Daher schließe ich das Ticket
