### ISSUE TITLE
Auftritts- / Probenorte bei Auftritten

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#444]
Wenn ich einen Auftritt neu anlege, kann ich als Ort nur die als Veranstaltungsort angelegten Locations auswählen. Wenn ich den Auftritt später bearbeite, kann ich auch Probenräume auswählen.
Da es oftmals Probenräume gibt, die auch Veranstaltungsorte sind, oder am Veranstaltungsort eine Generalprobe stattfinden kann, wäre es gut, wenn man entweder generell alle angelegten Orte auswählen könnte, oder bei der Anlage einer Location per Checkbox wählen kann, ob sie Veranstaltungsort, Probenraum, Studio ist - mit Mehrfachauswahl.
Ansonsten müssten Locations redundant angelegt werden.

**Comment by mattimaier** [comment]
Habe eine kleine Änderung in BNote 4 gemacht, die das Problem aber vermutlich schon löst. Bitte prüfen.

**Comment by ULinn** [comment]
Es lassen sich beim Anlegen von Proben nun alle Locations auswählen, egal als was sie angelegt waren. Das löst dieses Problem für's erste. Da es aber einige Orte gibt, die mehrere Funktionen haben, insbesondere Kirchen oder Mehrzweckhallen, die oft gleichermaßen Proben- wie Auftrittsort sind, wäre es sinnvoll, wenn eine Location mehrere Funktionen (Kategorien) haben könnte. Hat aber keine hohe Priorität.

**Comment by mattimaier** [comment]
Das Ticket #467 wurde neu angelegt. Dieses schließe ich dann, damit 4.0.0 nicht blockiert ist.
