### ISSUE TITLE
Groß- / Kleinschreibung bei "Passwort vergessen" ignorieren

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#445]
Wird bei der Benutzung des Passwort-Vergessen-Links bei der E-Mail eine falsche Groß-Kleinschreibung verwendet, erfolgt ein Hinweis auf eine unbekannte E-Mail-Adresse. Prinzipiell ist das natürlich korrekt - da aber bei E-Mail-Adressen die Groß-Kleinschreibung i.d.R. unerheblich ist, verwenden viele Nutzer das uneinheitlich. 
Hier wäre es sinnvoll, wenn Groß- / Kleinschreibung an dieser Stelle ignoriert würde.

**Comment by mattimaier** [comment]
Auf meinem Testsystem mti frischen alpha 2 Installation kann ich jetzt die E-Mail-Adresse Groß-/Kleinschreiben wie ich will, das geht.
