### ISSUE TITLE
Reihenfolge Anmeldungen anzeigen

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#446]
Aufgrund der Corona-Bedingungen gibt es aktuell oft Proben mit einer durch die Größe des Raumes begrenzten Teilnehmerzahl. Für die Entscheidung, wer teilnehmen darf, wäre es hilfreich, wenn man bei den Teilnehmerlisten von Proben und Auftritten zusätzlich zu den bisherigen Sortieroptionen auch nach Anmeldedatum sortieren könnte.
Eine Beschränkung der Probe / Veranstaltung auf X Teilnehmer wäre keine Option, da sich die max. mögliche Teilnehmerzahl oft erst kurzfristig ergibt bzw. nicht das einzige Kriterium für eine Teilnahme ist.

**Comment by mattimaier** [comment]
In BNote 4 gibt es neue Tabellen, daher könnte es damit von alleine gelöst sein. Bitte prüfen.

**Comment by mattimaier** [comment]
Jetzt habe ich es glaube verstanden. Bitte in der `update_db.php` die Zeile 258 auf `FALSE` stellen, wenn man das Skript nochmals ausführt, sonst sind die Module kaputt. Man muss das Skript allerdings ausführen um die beiden neuen Datenbankfelder einzufügen.

**Comment by ULinn** [comment]
... läuft bei mir. Super!

**Comment by ULinn** [comment]
Nach dem Monatswechsel sehe ich nun, dass falsch sortiert wird. Erst nach Monat absteigend, dann nach Tag aufsteigend (oder umgekehrt):
![chrome_2022-05-04_17-12-50](https://user-images.githubusercontent.com/1461623/166713340-df4e9cf9-185f-4a01-806a-8cf02d81452d.png) | ![chrome_2022-05-04_17-15-33](https://user-images.githubusercontent.com/1461623/166713487-621773b2-69ef-4b4e-8cfb-784de66c5159.png)
