### ISSUE TITLE
Anlegen von Ordnern mit "," im Share

### ISSUE THREAD

**Issue by pandeira** [mattimaier/bnote#450]
Es werden öfter mal Ordner mit "," im Share-Bereich angelegt. Bei Zugriffsversuch kommt dann eine Fehlermeldung. 

Wäre es möglich, beim Anlegen eines Ordners auf solche Zeichen zu prüfen und den Benutzer aufzufordern, einen Ordnernamen ohne "," zu verwenden? 
Es gibt nämlich keine Möglichkeit, einen solchen Ordner über die BNote-Oberfläche zu ändern oder zu löschen. Das muss dann immer jemand über das Filesystem des Servers machen.

**Comment by mattimaier** [comment]
Funktioniert jetzt:
![2022-04-01_13h50_05](https://user-images.githubusercontent.com/1818429/161257943-1a019a63-77db-4fd3-9fd6-92c3f42fc6c1.png)
![2022-04-01_13h50_52](https://user-images.githubusercontent.com/1818429/161257949-f2e0dfe0-bc0a-485a-8d05-7e1e5c98d1b6.png)
