### ISSUE TITLE
Reset-Password funktioniert nicht

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#458]
Beim Klick auf "Passwort vergessen" auf der Login-Seite kommt ein 500 Server Error. Fehlermeldung:

PHP Warning:  require(src/data/modules/forgotpassworddata.php): failed to open stream: Datei oder Verzeichnis nicht gefunden in /html/BNote/BNote/src/logic/controller.php on line 57

**Comment by mattimaier** [comment]
Soeben auf meinem Webhosting mit der neuen alpha2 getestet - sollte jetzt wieder gehen
