### ISSUE TITLE
Schwarze Schrift auf dunkelblauem Hintergrund in optionsbar

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#459]
Oben wird immer die Seitenüberschrift angezeigt (ID optionsbar), diese ist nahezu unlesbar, da schwarze Schrift auf blauem Grund.
Lösung: Schrift weiß

**Comment by mattimaier** [comment]
@ULinn Hast du mir nen Screenshot? Ich weiß nicht genau wo. Meine Optionsbar sieht so aus:
![2022-03-23_14h29_25](https://user-images.githubusercontent.com/1818429/159710645-2ebdbf17-6e7f-4ca8-a4a6-8836c9ca238e.png)

**Comment by ULinn** [comment]
![chrome_2022-03-23_14-33-48](https://user-images.githubusercontent.com/1461623/159711784-53156ea4-85b2-40dc-b51b-c1035aa5c730.png)
Sieht so aus, als ob bei mir Standard Bootstrap-Formatierungen angezeigt werden und bei Dir was anderes - evtl. wird da ein Stylesheet nicht korrekt eingebunden.

**Comment by ULinn** [comment]
Habe das Theme nun von "dark" auf "default" umgestellt - nun ist alles lesbar und deutlich besser gestyled ;-)
 Am besten entweder die anderen Themes anpassen oder beim Update Hinweis, dass aktuell nur das Default-Theme unterstützt wird.

**Comment by mattimaier** [comment]
Aus meiner Sicht ist hier eher das Thema, dass deine Styles gecached waren. In "dark" sieht es bei mir so aus:
![2022-03-24_09h16_18](https://user-images.githubusercontent.com/1818429/159872077-f79df661-8d5e-4f10-89b5-7901ce225be4.png)
Ich schließe dieses Thema.

**Comment by ULinn** [comment]
... hätte ich auch selbst drauf kommen können. Danke für den Hinweis.
