### ISSUE TITLE
Probenübersicht: Keine Anzeige Dirigent

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#460]
Im Menüpunkt "Proben" wird in der Liste bei Dirigent statt des Namens die Contact-ID angezeigt.

**Comment by mattimaier** [comment]
Sollte gefixt sein:
![2022-03-30_14h21_04](https://user-images.githubusercontent.com/1818429/160833226-12a1ce09-ca8b-4f3f-bec6-6d8a55d7aebc.png)
