### ISSUE TITLE
Frage: zu PHP Fehlermeldung im Webseiten LOG 

### ISSUE THREAD

**Issue by twobnt** [mattimaier/bnote#464]
Ich komme zwar inzwischen auf die Anmelde Seite, aber danach bleiben die Module "weiß, also ohne Inhalt.

hier die drei Fehlermeldung aus dem Log, Wahrscheinlich liegt der Fehler wieder auf meiner Seite,....

[Fri Mar 25 12:20:40.033978 2022] [fastcgi:error] [pid 3080941] [client 000.000.000.000:62440] FastCGI: server "/var/www/clients/client7/web63/cgi-bin/php-fcgi-*-443-domain.de" stderr: PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(../../lang.php) is not within the allowed path(s): (/var/www/clients/client7/web63/web/BNote:/var/www/clients/client7/web63/web:/var/www/clients/client7/web63/private:/var/www/clients/client7/web63/tmp:/var/www/domain.de/web:/srv/www/domain.de/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin) in /var/www/clients/client7/web63/web/BNote/src/data/data.php on line 2

[Fri Mar 25 12:20:54.624796 2022] [fastcgi:error] [pid 3083854] [client 000.000.000.000:62463] FastCGI: server "/var/www/clients/client7/web63/cgi-bin/php-fcgi-*-443-domain.de" stderr: PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(../../lang.php) is not within the allowed path(s): (/var/www/clients/client7/web63/web/BNote:/var/www/clients/client7/web63/web:/var/www/clients/client7/web63/private:/var/www/clients/client7/web63/tmp:/var/www/domain.de/web:/srv/www/domain.de/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin) in /var/www/clients/client7/web63/web/BNote/src/data/data.php on line 2, referer: https://domain.de/BNote/main.php?mod=login

[Fri Mar 25 12:20:54.673191 2022] [fastcgi:error] [pid 3083854] [client 000.000.000.000:62463] FastCGI: server "/var/www/clients/client7/web63/cgi-bin/php-fcgi-*-443-domain.de" stderr: PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(../../lang.php) is not within the allowed path(s): (/var/www/clients/client7/web63/web/BNote:/var/www/clients/client7/web63/web:/var/www/clients/client7/web63/private:/var/www/clients/client7/web63/tmp:/var/www/domain.de/web:/srv/www/domain.de/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin) in /var/www/clients/client7/web63/web/BNote/src/data/data.php on line 2PHP message: PHP Warning:  require(src/data/modules/Startdata.php): failed to open stream: No such file or directory in /var/www/clients/client7/web63/web/BNote/src/logic/controller.php on line 57, referer: https://domain.de/BNote/main.php?mod=login

Was mich wundert ist die Frage nach Groß und Kleinschreibung "PHP Warning:  require(src/data/modules/Startdata.php" ???

**Comment by mattimaier** [comment]
In 4.0.0 alpha 2 ist hier etwas verbessert worden. Allerdings scheint es ein Serverkonfigurationsproblem zu sein:
`open_basedir restriction in effect`
Ich vermute relative Pfade werden (warum auch immer) beim Import nicht erlaubt. Das wäre ein großer Umbau, wenn ich diese nicht mehr nutzen kann...
Mein Vorschlag: Probiere die Version 4.0.0 alpha 2 (kommt in den nächsten Tagen), dann sehen wir weiter.

**Comment by twobnt** [comment]
Danke, für die Info. habe mal "../../" mit eingefügt,....

bleibt noch folgende Fehlermeldung 

`[Tue Mar 29 13:40:52.180657 2022] [fastcgi:error] [pid 472930] [client 000.000.000.000:59319] FastCGI: server "/var/www/clients/client7/web63/cgi-bin/php-fcgi-*-443-domain.de" stderr: PHP message: PHP Warning:  require(src/data/modules/Startdata.php): failed to open stream: No such file or directory in /var/www/clients/client7/web63/web/BNote/src/logic/controller.php on line 57 `

was das Groß & Kleinschreibung Problem widerspiegelt.
das log fragt nach
src/data/modules/Startdata.php vorhanden ist aber nur
src/data/modules/startdata.php auf der Platte.

Benenne ich die Datei um,... komme ich drauf :-)

Werde die a2 testen :-D

**Comment by mattimaier** [comment]
Das freut mich. Da war ein unglückliches Refactoring der 4.0er Version vor dem alpha 2 Stand Schuld. Ich schließe das Ticket.
