### ISSUE TITLE
installation 4.0.0 alpha1 auf strato scheitert

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#465]
Die Neu-Installation von 4.0.0alpha1 (host ist strato) wird nicht durchgeführt. In der mysql-DB wird nur 1 table angelegt. Siehe screenshot
![bnote 400alpha1 install](https://user-images.githubusercontent.com/57803668/160114034-6d475310-e469-4540-b85c-b6d4c64a829d.jpg)
.

**Comment by mattimaier** [comment]
Jetzt habe ich die Installation von BNote 4.0.0 alpha 2 auf Strato getestet und nach ein paar Fixes hat es für mich funktioniert. Diese Fixes sind in der `install.php` und werden im nächsten Release enthalten sein.

**Comment by hermannluehrs** [comment]
nach installation von alpha02 läuft das script nicht durch. In der mysql-db wurden alle tabellen angelegt, aber ohne datendatz.

**Comment by mattimaier** [comment]
@hermannluehrs In der alpha 2 sind echt noch Fehler drin. Ich bin noch dran ein paar Dinge zu beheben...

**Comment by hermannluehrs** [comment]
installation alpha 3 auf strato klappt!
