### ISSUE TITLE
Aktuelle Probe wird doppelt angezeigt

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#466]
Im Menüpunkt Proben wird die kommende Probe einmal unter "Nächste Probe" angezeigt (korrekt) und dann nochmal direkt darunter bei "Weitere Proben". Korrekt wäre, die nächste Probe nur oben anzuzeigen. 
Oder die Überschrift von "Weitere Proben" in "Alle Proben" zu ändern.

**Comment by mattimaier** [comment]
In alpha3 prüfen: Anlage von Probenstrecke zeigt keine Erfolgsmeldung

**Comment by ULinn** [comment]
siehe #469

**Comment by mattimaier** [comment]
Da #469 geschlossen ist, mache ich dieses Ticket nun auch zu
