### ISSUE TITLE
4.0.0 alpha 3: Programmauswahl bei Auftritt fehlerhaft

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#468]
Beim Bearbeiten eines Auftritts stehen im Dropdown bei "Programm" nur als "Vorlage" gekennzeichnete Programme zur Verfügung. Es müssten dort aber alle Programme angezeigt werden.

**Comment by mattimaier** [comment]
Dies kann mit der alpha 4 (wenn verfügbar) getestet werden.

**Comment by ULinn** [comment]
Funktioniert bei mir in alpha 4
