### ISSUE TITLE
4.0.0. alpha 3: Falsche Anzeige bei vergangenen Probenphasen

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#470]
Beim Menüpunkt "Probenphasen" werden zunächst vergangene und zukünftige Phasen in der Liste angezeigt. Beim Klick auf "Vergangene Probenphasen" werden nur die zukünftigen angezeigt.

Korrekt wäre m.E: Bei der Auswahl des Menüpunktes werden nur aktuelle und zukünftige Phasen angezeigt, beim Klick auf "Vergangene Probenphasen" nur die abgeschlossenen.

**Comment by mattimaier** [comment]
In alpha 4 testen

**Comment by ULinn** [comment]
Funktioniert bei mir in alpha 4
