### ISSUE TITLE
Neuer Benutzer: Menüpunkte fehlen

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#473]
Ein in Alpha 4.1 neu angelegter Testnutzer (Mitglied in den gleichen Gruppen wie die anderen bestehenden Mitgliedern), sieht nach Login zunächst keine Menüpunkte in der linken Leiste. Nach Reload der Seite sieht er nur Share und Abstimmungen.

**Comment by mattimaier** [comment]
In der Konfigurationsdatei von BNote ist folgendes standardmäßig hinterlegt:
`<DefaultPrivileges>9,10,12,13,14</DefaultPrivileges>`
9 = Kontaktdaten --> siehe Icon oben
10 = Hilfe --> siehe Hilfe Icon oben
12 = Share --> passt
13 = Mitspieler --> klappt bei mir - kannst du bitte die Konfiguration bei dir prüfen?
14 = Abstimmung --> passt
Also hier sehe ich keinen Fehler.

Nach dem allerersten Login ist immer noch diese Zustimmungsgeschichte notwendig. Wenn man da klickt, dann sollte es eigentlich laden. Da habe ich aber schonmal festgestellt, dass es beim ein oder anderen ein Caching Problem gibt.

**Comment by ULinn** [comment]
Ich habe nun einen neuen Testbenutzer angelegt. Nach dem ersten Login wird die Datenschutz-Zustimmung angezeigt:

![chrome_2022-04-25_14-47-39](https://user-images.githubusercontent.com/1461623/165092327-4ad71bfb-d4f4-46f1-b828-6cd287c70b1e.png)

Beim Klick auf "Einverstanden" wird die Seite neu geladen, die Abfrage wird wieder angezeigt. Auch beim erneuten Versuch in einem Inkognito-Fenster passiert das gleiche.

**Comment by ULinn** [comment]
Der Klick auf "Nicht einverstanden" funktioniert allerdings, es kommt "Schade. Du kannst BNote somit nicht nutzen."

**Comment by ULinn** [comment]
Habe mit einem "alten" Benutzer getestet, bei den "Default Privileges" waren die Mitglieder nicht drin (aus Datenschutzgründen seinerzeit deaktiviert). Habe nun bei einem alten Benutzer die Berechtigung von Hand zugewiesen. Das hat funktioniert, allerdings scheint hier bei der Erfolgsmeldung noch SQL-Code mit angezeigt zu werden:

![chrome_2022-04-25_14-53-46](https://user-images.githubusercontent.com/1461623/165093702-47d34638-9b3d-4ebc-a113-53fc7a50c847.png)

Der Benutzer sieht nun die Mitgliedsdaten.

**Comment by ULinn** [comment]
Die Anzeige von E-Mail etc. stimmt mit den Einstellungen im Benutzerkonto überein. 

Was noch etwas stört, ist dass in den Mitglieder Kacheln immer "Funktion:" steht, auch wenn das jeweilige Mitglied keine Funktion hat (was bei den meisten der Fall ist) - in dem Fall könnte das Label entfallen.

**Comment by mattimaier** [comment]
Danke für das Feedback, diese beiden Punkte sollten gefixt sein.
