### ISSUE TITLE
Fehler in Abstimmungen

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#474]
In der Übersicht der Ergebnisse einer Abstimmung führt die Schaltfläche "Jetzt Abtimmen" zu der Fehlermeldung: " Fehler - Sie können an dieser Abstimmung nicht teilnehmen." Und zwar auch bei der Person, die die Abstimmung angelegt hat.

**Comment by mattimaier** [comment]
Ist die Person, die die Abstimmung angelegt hat in der Gruppe, die abstimmen soll mit drin?

**Comment by hermannluehrs** [comment]
ja, Fehlermeldung auch dann, wenn zur Gruppe gehörend.
