### ISSUE TITLE
Start: Nachrichten:  automatische Registrierung

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#475]
Die Meldung "Die automatische Registrierung ist aktiviert. Bitte Sicherheitshinweise beachten." erscheint im Start-Bildschirm auch dann, wenn die automatische Registrierung deaktiviert ist.

**Comment by mattimaier** [comment]
Leider kann ich das Problem nicht nachstellen @hermannluehrs . Hast du mal versucht die Konfiguration zu ändern, zu speichern und wieder zurück zu ändern und nochmal zu speichern.

**Comment by hermannluehrs** [comment]
Die Meldung erscheint, wenn man sich als Administrator anmeldet.

**Comment by mattimaier** [comment]
Auf Testsystem ausprobiert und an der Konfiguration mehrmals gedreht. Die Darstellung auf der Startseite war nun der Konfiguration entsprechend.
