### ISSUE TITLE
feature request: Datumfelder mit Formathinweis hinterlegen

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#476]
In den meisten Datumfeldern ist das Format yyyy-mm-dd T hh:mm:ss nötig, aber es gibt keinen Hinweis auf das Format. Besser wäre ein Hinweis in allen leeren Datumfeldern auf das jeweils geforderte Format.

**Comment by mattimaier** [comment]
Welche Felder meinst du genau? Welchen Browser verwendest du?

**Comment by hermannluehrs** [comment]
MacOSX, Safari. Es betrifft zB Feld für Abstimmungsende.

**Comment by mattimaier** [comment]
Hm. Ich habe es jetzt mit folgenden Geräten probiert:
* MacBook Air M1: Safari
* iPhone
* iPad Pro
* Windows Chrome
* Windows Firefox
* Windows Edge
Alle haben bei mir für die Anlage von Proben und Abstimmungen sowie Datumsoptionen dort funktioniert. Ich kann das Problem bei mir also nicht reproduzieren. Hat noch jemand das Problem?

Meine Vermutung: Du nutzt eine alte Safari-Version. Es ist mindestens Safari 14.1 notwendig:
https://caniuse.com/input-datetime

**Comment by hermannluehrs** [comment]
deine vermutung stimmt: ich nutze safari 12.1.2 auf mac os 10.12.6 (sierra). dort werden auch keine datum-input widgets angezeigt
mit dem aktuellen firefox 100.0 auf mac os x sierra gibt es keine probleme: die datumfelder enthalten im feld den format-hinweis und das widget poppt auf.

von daher: nice to have für alte safari-versionen auf mac-laptop oder mac-pc , aber kein muss.
