### ISSUE TITLE
Request: Modul Webseite

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#478]
Das Fehlen des Webseiten-Moduls inkl. Gallery verhindert derzeit den Umstieg von 3.4 auf 4.0, denn unser Chor nutzt das für Hinweise auf der öffentlichen Internetseite. Auf der sind bnote-inhalte als frames eingebunden. Ich fände die Wiederherstellung in 4.x sehr gut und rege das an. Merci!

**Comment by mattimaier** [comment]
Welche Funktionen werden genau benötigt/genutzt? Aus verschiedenen Gründen, möchte ich verhindern ein CMS wie es sehr viele da draußen gibt nochmals nachzubauen...

**Comment by hermannluehrs** [comment]
Die öffentliche Webseite (verdichor.de) bettet diese drei Inhalte als frames (externer inhalt) ein:

https://verdichor-intern.de/BNote/data/webpages/box1.html
https://verdichor-intern.de/BNote/data/webpages/box2.html
https://verdichor-intern.de/BNote/data/webpages/box3.html

Erzeugt werden die Inhalte in bnote. Es handelt sich um Text und images. Die images liegen in einer gallery. Siehe screenshots am Beispiel von box2.html

Mehr wird nicht gebraucht.

**Comment by mattimaier** [comment]
Da könnte man vermutlich eine einfache Lösung für finden:
* Seiten anlegen
* vorhandene Seiten Bearbeiten
* Anhänge hochladen und öffentlich zur Verfügung stellen

**Comment by hermannluehrs** [comment]
Ich sehe, dass das Request "Modul WebSeite" nicht mehr dem Milestone 4.1.0 zugewiesen ist. Dabei wird es jetzt immer dringender, dass es das feature wieder gibt. Denn unser webhoster (strato) verlangt inzwischen die Nutzung der php-version 8. Bnote 3 läuft damit nicht. Bnote 4 hat das Modul nicht mehr.  Es wäre also super wichtig, dass in Bnote 4 das Modul "Web-Seite" wieder eingerichtet wird. Gern minimalistisch wie oben skizziert. Können wir damit rechnen, dass das (absehbar) kommt?

**Comment by hermannluehrs** [comment]
Lieber Matti,Ich hab die Anfrage auf GitHub auch eingestellt, hier aber noch mal per Mail direkt an dich.: kannst du sagen, ob und wann das Modul Webseite in B Note 4.xverfügbar wäre? Ohne dieses Modul könnte verdichor.de bnote nicht mehr nutzen. Wir brauchen bald eine Perspektive. Vielen Dank beste Grüße aus Berlin, HermannAm 16.05.2022 um 22:40 schrieb Hermann Lührs ***@***.***>:﻿Die öffentliche Webseite (verdichor.de) bettet diese drei Inhalte als frames (externer inhalt) ein:https://verdichor-intern.de/BNote/data/webpages/box1.htmlhttps://verdichor-intern.de/BNote/data/webpages/box2.htmlhttps://verdichor-intern.de/BNote/data/webpages/box3.htmlErzeugt werden die Inhalte in bnote. Es handelt sich um Text und images. Die images liegen in einer gallery. Siehe screenshots am Beispiel von box2.htmlMehr wird nicht gebraucht.Am 16.05.2022 um 18:03 schrieb Matti Maier ***@***.***>:Welche Funktionen werden genau benötigt/genutzt? Aus verschiedenen Gründen, möchte ich verhindern ein CMS wie es sehr viele da draußen gibt nochmals nachzubauen...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.<box2 in bnote.jpg>

**Comment by hermannluehrs** [comment]
Habe das beta 4.02 installiert (auf ein neu installiertes 4.00 / update 4.01). Das Website-Modul erscheint und lässt sich bearbeiten. Eine Bilddatei (jpg) einzubinden, hat noch nicht geklappt. Es wir in der Vorschau ein Rahmen für das Bild angezeigt, nicht aber das Bild selbst. Ich probiere weiter. Hat jemand einen Hinweis?

**Comment by mattimaier** [comment]
siehe #533
