### ISSUE TITLE
Kalender-Export enthält alle Mailadressen

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#480]
Wenn ich über den Button "Kalender-Export" auf der Startseite eine .ics-Datei exportiere, enthält diese die E-Mail-Adressen aller eingeladenen Teilnehmer. Ich bin kein Experte, aber ich kann mir nicht vorstellen, dass die DSGVO damit einverstanden ist - und meine Chormitglieder sind es auch nicht. 

Wenn die .ics-Datei dann von irgendjemand in Outlook importiert wird und dort eine Änderung vorgenommen wird, werden u.U. alle Mitglieder über diese Änderung informiert - ebenfalls nicht wünschenswert.

Lösung 1: Teilnehmeradressen haben im .ics-File nix zu suchen. Falls das für igendejemanden wichtig ist, dann
Lösung 2: Es werden nur die E-Mail-Adressen verwendet, deren Inhaber der Weitergabe zugestimmt haben.
Lösung 3: Kalender-Export komplett abschalten.

**Comment by mattimaier** [comment]
Ich denke die Lösung 2 ist gut.

**Comment by mattimaier** [comment]
Hier sind nun die Einstellung im Export ebenfalls berücksichtigt:
![2022-07-06_21h12_00](https://user-images.githubusercontent.com/1818429/177625389-0b1313b8-785a-4928-aa00-5e9fbc0e13f7.png)
