### ISSUE TITLE
"Kalender-Abonnieren" aktualisiert nicht.

### ISSUE THREAD

**Issue by ULinn** [mattimaier/bnote#481]
Werden Änderungen an Proben vorgenommen, scheinen diese nicht beim abonnierten Kalender berücksichtigt zu werden.

Beispiel: Ich lege eine Probe mit Probenort X an. Die Probe erscheint in meinem Google-Kalender, der mit webcal://URL/BNote/src/export/calendar.ics?user=MEINEID verbunden ist. Danach ändere ich den Probenort auf Y ab. Im Google-Kalender steht weiterhin Probenort X.

Um sicherzustellen, dass es nicht an der Aktualisierung bei Google liegt, habe ich den Kalender aus Google entfernt, den Link neu eingebunden - es wird immer noch Probenort X angezeigt.

Beispiel 2: Ein Auftritt, bei dem vermutlich zunächst eine falsche Startzeit angegeben und dann gleich wieder geändert wurde, wird auch Wochen nach dem Anlegen im neu abonnierten Kalender mit der falschen Uhrzeit angezeigt.

**Comment by ULinn** [comment]
Im Kalender im BNote-Backend werden alle Termine korrekt angezeigt.

**Comment by mattimaier** [comment]
Mit dem Google-Caching hatte ich selbst in der Vergangenheit viele Probleme. Ich prüfe nochmals ob hier der Export richtig funktioniert (z.B. über Postman), aber was beim Import durch einen Cal-Server passiert, habe ich nicht im Griff.

**Comment by mattimaier** [comment]
**Test**
Vorher in BNote 4.0.0
![2022-06-04_22h21_43](https://user-images.githubusercontent.com/1818429/172024457-f6308e61-99ec-4e78-ba7d-cc9d97b80e07.png)
Abruf über Schnittstelle:
![2022-06-04_22h22_36](https://user-images.githubusercontent.com/1818429/172024469-46fa3571-86c9-404a-a666-77ffd6ca4b8d.png)

Änderung in BNote:
![2022-06-04_22h23_23](https://user-images.githubusercontent.com/1818429/172024483-28ac107e-8830-4feb-bfae-a6297177e288.png)
Abruf über Schnittstelle:
![2022-06-04_22h23_53](https://user-images.githubusercontent.com/1818429/172024494-a33a156f-e17a-44c9-a10e-e532117ae90b.png)

Aus meiner Sicht gibt es hier nichts zu ändern.
