### ISSUE TITLE
Neuer Nutzer: Datenschutzerklärung wird nicht verarbeitet

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#483]
Ein neu angelegter Nutzer (Kontaktdaten sind zugeordnet und Nutzer ist aktiv gesetzt) wird beim Einloggen aufgefordert, den Datenschutzbestimmungen zuzustimmen. Die Auswahl "Zustimmung" führt nicht dazu, dass das System genutzt werden kann. (webhoster ist strato, php 7.4. Das Problem besteht auf ios 15.5 safari, mac firefox 100, windows 10 chrome). Erst wenn ich manuell in der mysql-Datenbank den Eintrag in gdpr_ok auf 1 setze, ist der Zugang möglich.

**Comment by mattimaier** [comment]
Die Anlage eines neuen Benutzers und das Freischalten mit den Zugangsdaten hat nun funktioniert.

**Comment by hermannluehrs** [comment]
funktioniert such bei mr.
