### ISSUE TITLE
Beim Bearbeiten von einem Auftritts-Teilnehmer wird die Teilnahme für alle gesetzt

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#484]
Steps to reproduce:
1. Auftritt auswählen
2. auf "Teilnehmer anzeigen" klicken
3. auf "Teilnahme bearbeiten" klicken
4. Teilnahme für _einen_ Eintrag ändern

-> Teilnahme wird für alle eingeladnen Mitspieler auf _nein_ gesetzt

<img width="1727" alt="Screenshot 2022-05-24 at 09 16 17" src="https://user-images.githubusercontent.com/2054402/172172144-9c355ff8-165f-4970-91ab-01dd02051641.png">

**Comment by mattimaier** [comment]
Auf dem Testsystem verschiedene Konfigurationen versucht und da funktioniert das Editieren der Teilnahme eines Auftritts nun problemlos.
