### ISSUE TITLE
Fehlendes Padding für Buttons

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#485]
1. Kein Padding zwischen Icon und Text in Buttons
2. Kein Padding nach auße
<img width="1160" alt="Screenshot 2022-06-06 at 15 43 59" src="https://user-images.githubusercontent.com/2054402/172173000-2196e66b-1d40-46ef-badf-4d645311bdda.png">
n

**Comment by mattimaier** [comment]
@sotpt Bitte den gesamten `BNote/style` Ordner löschen und nochmals neu einfügen. Außerdem bitte Caches leren. Der Screenshot sieht ziemlich kaputt aus.
