### ISSUE TITLE
BNote Logo ist unscharf auf @2x/@3x Geräten

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#488]
Pixel-Grafik durch Vektor-Grafik ersetzen 
![IMG_B221D6ED9CFA-1](https://user-images.githubusercontent.com/2054402/172174343-53cda78d-8c41-4024-9a3c-3476460b7d1b.jpeg)

**Comment by mattimaier** [comment]
@sotpt Kannst du mir bitte die Logos neu rauslassen. Du hast die gemacht.
