### ISSUE TITLE
Auftritt -> Infos: Zeilenumbrüche werden nicht dargestellt 

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#489]
<img width="1699" alt="Screenshot 2022-06-06 at 15 57 59" src="https://user-images.githubusercontent.com/2054402/172175415-76d4fa4b-8a39-4de5-ac1e-022f36c5b978.png">
<img width="726" alt="Screenshot 2022-06-06 at 15 56 31" src="https://user-images.githubusercontent.com/2054402/172175430-867e628c-0efb-4d96-9171-29e42b6d5fc8.png">
<img width="1288" alt="Screenshot 2022-06-06 at 15 56 00" src="https://user-images.githubusercontent.com/2054402/172175434-386aebda-167c-45fb-9a0c-b1ac85a0132e.png">

**Comment by mattimaier** [comment]
@sotpt Du hast irgendwo die Styles nicht richtig geladen oder beim Update ging was schief. So sollte der eigentliche "Neuer Auftritt" Screen aussehen:
![image](https://user-images.githubusercontent.com/1818429/174299881-c1d45cbb-0a3e-416c-8326-462c26b1e350.png)

Das Zeilenumbruchsthema schaue ich mir noch an...

**Comment by mattimaier** [comment]
Sieht auf meinem Testsystem ziemlich gut aus:
![2022-07-06_20h58_27](https://user-images.githubusercontent.com/1818429/177623259-1c85a57c-176e-4c04-b549-09663df16a12.png)
![2022-07-06_20h58_52](https://user-images.githubusercontent.com/1818429/177623267-8e1d7869-8e56-4022-910e-64b5ece90123.png)
