### ISSUE TITLE
Top-Bar sieht kaputt aus, wenn das Ensemble einen langen Namen hat

### ISSUE THREAD

**Issue by sotpt** [mattimaier/bnote#491]
<img width="1229" alt="Screenshot 2022-06-06 at 19 27 09" src="https://user-images.githubusercontent.com/2054402/172213461-4c0abdb2-ce7b-4d14-9273-110ce5ec29f4.png">

Vorschlag: 
a) Linke und rechte Bar könnten die selbe Farbe haben
b) Zeilen-Umbruch und dynamische Schriftgröße für die Sidebar

**Comment by mattimaier** [comment]
Jetzt sieht es so aus:
![2022-06-17_14h35_37](https://user-images.githubusercontent.com/1818429/174299553-4aa7da4c-716a-4c26-86c0-c2c2b1c54302.png)
