### ISSUE TITLE
Share Lesemodus für Nichtadministratoren: Fehler

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#492]
Wenn die Konfiguration auf Ja gesetzt wird, ist auch Administratoren der Schreibzugriff auf Share verwehrt (auch dann, wenn in den user-privileges des Administrators admin aktiviert ist).

**Comment by mattimaier** [comment]
Auf Test/Staging-System werden die Berechtigungen richtig angewandt, d.h. Admins können mit der Konfigurationsoption noch schreiben, aber User nicht mehr.
