### ISSUE TITLE
Http Error 500 nach Update auf BNote 4

### ISSUE THREAD

**Issue by HenningKuehl** [mattimaier/bnote#494]
Nachdem ich versucht habe BNote 3.4 auf meinem Server auf BNote 4.0 zu aktualisieren funktioniert die Anwendung leider nicht mehr.
Im Browser wird lediglich ein `HTTP ERROR 500` angezeigt. Auch in der Konsole gibt es keine detailliertere Fehlermeldung.

Folgende Schritte habe ich ausgeführt um BNote zu aktualisieren:
1. .zip-Datei heruntergeladen
2. `BNote/src`, `BNote/style` und `BNote/lib` auf dem FTP-Server gelöscht
3. Alle Dateien aus der .zip-Datei auf den Server geladen und dabei alle existierenden Dateien überschrieben
4. `update_db.php` einmalig ausgeführt
5. `update_db.php` und `install.php` auf dem FTP-Server gelöscht

Die BNote-Instanz ist unter [bnote.mv-wuellen.de](http://bnote.mv-wuellen.de) erreichbar, falls das bei der Fehlersuche hilft.
Zudem ist mir aufgefallen, dass in der `readme.txt` in der .zip-Datei andere etwas Informationen zur Aktualisierung stehen als in den Release-Notes zur Version.

**Comment by dnop-software** [comment]
Auch bei mir hat das Einspielen des Updates dazu geführt, dass BNote überhaupt nicht mehr nutzbar ist. Genau wie [HenningKuehl] habe ich die Updateschritte in den Release Notes genau befolgt.
Ich bekomme allerdings keinen HTTP Error 500 sondern eine PHP Fehlermeldung:

Parse error: syntax error, unexpected end of file in [...]/BNote/src/presentation/widgets/field.php on line 350

Würde ein temporäres Downgrade auf Version 3.4 funktionieren, oder ist das nicht mehr möglich nachdem `update_db.php` ausgeführt wurde?

**Comment by mattimaier** [comment]
Ein paar Dinge bitte noch prüfen, dann bekommen wir das wieder hin:
1. Könnt ihr PHP auf 7.4 updaten?
2. Bitte die Server Logs mal auslesen, d.h. je nach eurem Hoster findet ihr die irgendwo anders. Wenn ihr direkt Zugriff auf den Server habt, dann oft unter `/var/log/apache` und mal schauen. Dort stehen dann oft genauere Fehlermeldungen

Die `field.php` ist eine sehr zentrale Datei. Wenn es da ein Problem gibt, bitte einfach mal die aktuelle von hier aus dem Repo nehmen: https://github.com/mattimaier/bnote/blob/master/BNote/src/presentation/widgets/field.php

Downgrade ist eigentlich gut möglich. Man kann auch die Änderungen aus der `update_db.php` relativ leicht rückgängig machen. Empfehlen würde ich das nicht (Sicherheit von 4.0 deutlich besser).
