### ISSUE TITLE
Kein Administrator nach Update

### ISSUE THREAD

**Issue by dnop-software** [mattimaier/bnote#496]
Beim Update auf BNote 4.0.0 werden einige neue Module angelegt, unter anderem auch ein neues Admin Modul. Allerdings bekommen anscheinend nur Superuser Rechte für die neuen Module.
Bei uns war kein Superuser in `config.xml` konfiguriert, deshalb hatte nach dem Update niemand mehr Administratorzugriff. An des Benuztermodul kam man auch nicht mehr dran, weil das Admin Modul vorgeschaltet war.
Zugriff auf das Admin Modul ließ sich nur durch manuelles Bearbeiten der Datenbank wiedererlangen.

Vielleicht habe ich etwas falsch gemacht. Falls ich aber nicht der einzige bin, der dieses Problem hatte, sollte das Update Script überarbeitet werden. Ein möglicher Weg wäre zum Beispiel, all denen Admin Zugriff zu geben, die vor dem Update schon Zugriff auf das Modul Konfiguration hatten.

**Comment by dnop-software** [comment]
Noch eine Idee dazu: Das neue Admin Modul scheint ja eher eine Vorschaltseite für die anderen Module aus der Admin Kategorie zu sein. Wäre es vielleicht sinnvoll, das Admin Modul automatisch freizuschalten, sobald ein Benutzer Zugriff auf ein Modul aus der Kategorie Admin hat?

**Comment by mattimaier** [comment]
**Update-Problem**
Mit [diesem Commit](https://github.com/mattimaier/bnote/commit/cca97194108f6ff7cfeb1d3efa2309cddbc669b1) müsste das Problem bereits behoben sein.

**Vorschaltseite**
Das ist eigentlich so gebaut, aber dafür muss die Basiskonfiguration stimmen. Diese war nach dem 3.4.x Update kaputt - sorry.
