### ISSUE TITLE
Probenteilnehmer ohne Rückmeldung werden als abgesagt angezeigt

### ISSUE THREAD

**Issue by dnop-software** [mattimaier/bnote#504]
In der Teilnehmer Ansicht einer Probe werden alle eingeladenen Teilnehmer, die noch keine Rückmeldung gegeben haben in der Liste "Erhaltene Zu-/Absagen" mit "nein" aufgeführt. Die Liste "Ausstehende Zu-/Absagen" bleibt hingegen leer.
Lediglich aus der letzten Tabelle "Zusammenfassung" geht hervor, dass gar nicht so viele Teilnehmer abgesegt haben, wie es in der ersten Tabelle aufgeführt ist.

Erwartet hätte ich, dass in der ersten Tabelle wirklich nur die Teilnehmer aufgeführt sind, die auch eine Rückmeldung abgegeben haben.

**Comment by mattimaier** [comment]
Leider kann ich den Fehler gerade nicht wirklich nachvollziehen:
<img width="1217" alt="Bildschirmfoto 2023-05-06 um 14 08 24" src="https://user-images.githubusercontent.com/1818429/236623166-fafbaeed-d02c-42ce-984c-0b8d7f10e8f2.png">

**Comment by dnop-software** [comment]
Ich kann das Problem mittlerweile auch nicht mehr reproduzieren. Wahrscheinlich ist es durch ein früheres Update schon behoben worden.
