### ISSUE TITLE
beta 4.02 / Modul website

### ISSUE THREAD

**Issue by hermannluehrs** [mattimaier/bnote#533]
Jetzt funktioniert es: Habe das beta 4.02 installiert (auf ein neu installiertes 4.00 / update 4.01). Das Website-Modul erscheint und lässt sich bearbeiten. Eine Bilddatei (jpg) einzubinden (mit img src/Pfad.../bild.jpg) klappt mit relativem pfad. Das Bild wird angezeigt

In der config.xml ist die Option UseGallery noch vorhanden,es macht anscheinend keinen Unterschied ob auf True oder False.

**Comment by mattimaier** [comment]
Ja, die config.xml hat noch diese Option, welche ich nicht kompliziert entfernen möchte. Das ist eben eine kleine Altlast. Aber es freut mich, dass es funktioniert :-)

**Comment by hermannluehrs** [comment]
Wann kommt denn das gültige 4.02 Release?
