### ISSUE TITLE
Website Modul wird z.T. mehrfach in Navigation angezeigt

### ISSUE THREAD

**Issue by mattimaier** [mattimaier/bnote#537]
Fehleranzeige bei einem Nutzer:
![Bildschirmfoto 2023-04-14 um 07 37 05](https://user-images.githubusercontent.com/1818429/231950810-58632e58-16fb-44a5-93b2-8e69c63a185c.png)

**Comment by mattimaier** [comment]
Das Problem ist einfach zu lösen:
In der Tabelle `module` sind vermutlich mehrere Einträge mit "Website" als name. Einfach alle _überschüssigen_ Einträge entfernen. Es ist egal welche ID weiterexistiert. Da dies nur wenige Benutzer trifft, wird kein separater Code für die Lösung des Problems erstellt.

**Comment by hermannluehrs** [comment]
Funktioniert!
