### ISSUE TITLE
Installationsanleitung outdated/missverständlich?

### ISSUE THREAD

**Issue by Hannfeld** [mattimaier/bnote#544]
Mein Chorleiter und ich sind nach Lesen der diversen Installationsanleitungen unabhängig voneinander zu dem Schluss gekommen, dass man bei Neuinstallation erst die Hauptversion installierren und dann erst die Patches anwenden muss. Das hat bei mir nicht funktioniert, weil die Hauptversion diverse Probleme bereitet hat und ich gar nicht bis zum Patchen gekommen bin. 
Nach einigem Trial und Error habe ich die App jetzt zum laufen gekriegt, indem ich das genaue Gegenteil gemacht habe: erst die Patch-Dateien nacheinander in die Hauptversion kopiert und dann die App auf dem Server installiert.
Gute App btw, daher wäre es um so schöner, wenn der Installationsprozess etwas zugänglicher wäre :-D

**Comment by mattimaier** [comment]
Danke @Hannfeld für das Feedback. In 4.0.0 gab es einige Probleme, trotz ausführlichen Tests, u.a. auch mit Usern. Sobald das nächste Patch-Release da ist, mache ich wieder eine vollständige Installationsdatei und dann dürfte das viel einfacher sein.

**Comment by mattimaier** [comment]
Jetzt habe ich auch noch die Website aktualisiert. Im Prinzip ist das Wiki hier in GitHub die korrekte und überall referenzierte Installationsanleitung.
